---
packages:
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    ODNlZmQ2ZGE2OGYzMTFhZGFiYzg0OTMxOGU1NjcxMjczODU3YTdjZg==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: converger
  version: !binary |-
    ZWMwY2NjNDM0NGE2NjZjMDVjZTMwMWQ4MGY0YzllNjA0NDE5NDRhNw==
  sha1: !binary |-
    NjViNTA1ZDMzOGVhYWYxMDY4MjA4MzYyZjMwODZkNTA0ZTg3MmE3Zg==
  fingerprint: !binary |-
    ZWMwY2NjNDM0NGE2NjZjMDVjZTMwMWQ4MGY0YzllNjA0NDE5NDRhNw==
  dependencies:
  - golang
- name: docker-circus
  version: !binary |-
    NjQxMjVmM2M2Y2EwMDZmNzhlZTFjYWVhZTJjYzZjMjE4MzIzNWFhZQ==
  sha1: !binary |-
    MDM4NTk4ZjZlNjc5NTI5MzYzMjQ2OWI2NjA2MzA0NTEwZDcxMDE0OQ==
  fingerprint: !binary |-
    NjQxMjVmM2M2Y2EwMDZmNzhlZTFjYWVhZTJjYzZjMjE4MzIzNWFhZQ==
  dependencies:
  - golang
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    MGFhZmI4ZDU0M2M3YTExNDdhYzdkMGFhNmMzMzg1NDQyNjRiNjM1MQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: linux-circus
  version: !binary |-
    NDA5YTcxMjY1NDk2YzNhMzMyNmUwODc5MDQxN2MxZWM2NmZmYjdmNA==
  sha1: !binary |-
    MzZhMjhhNTdhZjcwN2FjMTkzYmFlMjlmOWMxY2JhMDk2MjYwYmFkNg==
  fingerprint: !binary |-
    NDA5YTcxMjY1NDk2YzNhMzMyNmUwODc5MDQxN2MxZWM2NmZmYjdmNA==
  dependencies:
  - golang
- name: smoke-tests
  version: !binary |-
    ZGZiZjU4OGEzZGY0YzJlNGUzNjgyN2Y1MTA1NWMwNjE4MTc1YTI2Nw==
  sha1: !binary |-
    ZTFiYzg5ZjJhZDRjMmJjMjJkZWE5MzMzMzQ5NWE5MTU5YWJmODFmMw==
  fingerprint: !binary |-
    ZGZiZjU4OGEzZGY0YzJlNGUzNjgyN2Y1MTA1NWMwNjE4MTc1YTI2Nw==
  dependencies:
  - golang
- name: etcd_metrics_server
  version: !binary |-
    MDgzZjA0NGU4MmQ3YzAxY2UyZDcyZDg0MzFlMTJkNWQyNjBhNjY2OQ==
  sha1: !binary |-
    NzE1ZTMxYjUxNTdlYTIzYmM1YTQxNDQ2ZTllNTliMDM4NTYwZjExNA==
  fingerprint: !binary |-
    MDgzZjA0NGU4MmQ3YzAxY2UyZDcyZDg0MzFlMTJkNWQyNjBhNjY2OQ==
  dependencies:
  - golang
- name: executor
  version: !binary |-
    ZTQxOTkwYmUyMWMwZmU0N2JjYTYyN2EyMzY3Mzg0MGQ0OTQ4YWU1Nw==
  sha1: !binary |-
    ZGZkZDZlZjEwY2ZlM2VhOGIzNTZhMzE2NjlkNDAzYTRjMDE0NDNlNg==
  fingerprint: !binary |-
    ZTQxOTkwYmUyMWMwZmU0N2JjYTYyN2EyMzY3Mzg0MGQ0OTQ4YWU1Nw==
  dependencies:
  - golang
- name: acceptance-tests
  version: !binary |-
    YWNlNzY4NTE5OGNiZmJlYjQ3OWY5MGI1NDlhOWIyNjg1NzllYTVmNA==
  sha1: !binary |-
    N2IxNjZlMWNmNmNhN2M3ZWZmZTFkODVmOTNhYjlmZWQ1YThjYjYxYw==
  fingerprint: !binary |-
    YWNlNzY4NTE5OGNiZmJlYjQ3OWY5MGI1NDlhOWIyNjg1NzllYTVmNA==
  dependencies:
  - golang
- name: receptor
  version: !binary |-
    ZGQ4ZmM0NzQ5NjkxZTJkZWQ1MGVkYzZhNDFhYTZhYTA1YjVhOGMzNQ==
  sha1: !binary |-
    ZDc3MGRiOGZmYjAyM2QyN2I4ZDRiYTZkYTJmMDQ4OTEyM2JhMjFkNw==
  fingerprint: !binary |-
    ZGQ4ZmM0NzQ5NjkxZTJkZWQ1MGVkYzZhNDFhYTZhYTA1YjVhOGMzNQ==
  dependencies:
  - golang
- name: rootfs_lucid64
  version: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  sha1: !binary |-
    NGUyOTNiNWQwMjBkNmRiZGVhN2FmMjZhYmUzZTRmMDg2NGJjNjFmMg==
  fingerprint: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  dependencies: []
- name: rep
  version: !binary |-
    OTBmNjY1MzJlNTZhODQ5ZWY2ODMzMDYzNDRkNjM3ODlkZmUwZmI2Ng==
  sha1: !binary |-
    MDYzOGMyODY3NmVmZDE1YjEyNDI1ODcxYWIwYWVjN2I5Zjk4YjQwYQ==
  fingerprint: !binary |-
    OTBmNjY1MzJlNTZhODQ5ZWY2ODMzMDYzNDRkNjM3ODlkZmUwZmI2Ng==
  dependencies:
  - golang
- name: etcd
  version: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  sha1: !binary |-
    NjdlMWM4Yjk1YzhiNWMzMmIxZjg5ZjNjMjc1YmQ5ZjYxNmExZDc2Yw==
  fingerprint: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  dependencies:
  - golang
- name: file_server
  version: !binary |-
    N2IyYjNhOWM4N2UyMDJmNjM3NzdhZDkyMTA3ZDhiYmNiNGU0MGNhZA==
  sha1: !binary |-
    YmYyZDhiNjMzZWUxZDQ4NzYzMjc1OTdjZjcxZmMxM2Q3MDEzMGYxZg==
  fingerprint: !binary |-
    N2IyYjNhOWM4N2UyMDJmNjM3NzdhZDkyMTA3ZDhiYmNiNGU0MGNhZA==
  dependencies:
  - golang
- name: route_emitter
  version: !binary |-
    YzlmYWQzYTNiOWFhYWE4NmVkMGI3MGZiNzgxYTViNjdlMDgyYzVhZg==
  sha1: !binary |-
    YzdiNjJjZmMxZWQ3NDdmY2FjZWE4YzY2NWM2ZTNjZmRhNWJkMzQ5ZQ==
  fingerprint: !binary |-
    YzlmYWQzYTNiOWFhYWE4NmVkMGI3MGZiNzgxYTViNjdlMDgyYzVhZg==
  dependencies:
  - golang
- name: tps
  version: !binary |-
    MTFhODRjOWFmZWUyYTRlZWIxN2ZhZTg2MmQ1YjU5ZmIzNWU5OTViNw==
  sha1: !binary |-
    OTAzZmQxN2I5MjZiNmYxNTEyYmJmMzNjNmYyYTYwOTU2ZDIyY2YxZg==
  fingerprint: !binary |-
    MTFhODRjOWFmZWUyYTRlZWIxN2ZhZTg2MmQ1YjU5ZmIzNWU5OTViNw==
  dependencies:
  - golang
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MTUxMjA2NjY3ZmI0MjQzMTUzYjUwODA2ZTk3YjFmYjdkZTlhOTRjZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: auctioneer
  version: !binary |-
    ZjBlYjYyYWNlYmMyYzNlNmJhMzczMGRhNTRlYjZmMjM3NDI0NDAxNQ==
  sha1: !binary |-
    ZWYzMTA5NDZjZGJhNTgxYWNiNjNmYjExYmFhMzgzMTcyMGQ3ZWZkNw==
  fingerprint: !binary |-
    ZjBlYjYyYWNlYmMyYzNlNmJhMzczMGRhNTRlYjZmMjM3NDI0NDAxNQ==
  dependencies:
  - golang
- name: nsync
  version: !binary |-
    MmE1ODZjZmMwMmY0MmM3MzU4YmJlMGRjYjQ4OTNlZDc5NGQ0NjY4Mw==
  sha1: !binary |-
    ZmE3OTA1Zjg4MWY0Y2FjMTYwYzA3MjgxM2U5NTVmNWJhNTM4YjczMg==
  fingerprint: !binary |-
    MmE1ODZjZmMwMmY0MmM3MzU4YmJlMGRjYjQ4OTNlZDc5NGQ0NjY4Mw==
  dependencies:
  - golang
- name: cf-cli
  version: !binary |-
    NjQ1YjY5NTA1MmUzOWJlZGVhNWI3MTdkZDk5MzYwZWY1ZjQ5MmJkZA==
  sha1: !binary |-
    MzQ5MDAxMDdiZWI3NDdlZjQxNjQ1ZTBjYTcxZmE5OTgyNGQwNTgxOQ==
  fingerprint: !binary |-
    NjQ1YjY5NTA1MmUzOWJlZGVhNWI3MTdkZDk5MzYwZWY1ZjQ5MmJkZA==
  dependencies: []
- name: stager
  version: !binary |-
    Yzk4NmVjZWIwYzNiOWIxNGFlM2QyNzZlZjVjMDE5MmI4ODE4MjZkNQ==
  sha1: !binary |-
    M2RhMDQ1NzU5ODU4ZWE3Yjk5MzE2ZjQ3ZmViMDk5MjA2MTkzY2YwMw==
  fingerprint: !binary |-
    Yzk4NmVjZWIwYzNiOWIxNGFlM2QyNzZlZjVjMDE5MmI4ODE4MjZkNQ==
  dependencies:
  - golang
- name: runtime_metrics_server
  version: !binary |-
    MWZjZjQ1MzE2MmY0NzA1NmMxYjI4MzRkN2NkOTZkNmNkZWM3MGJkNQ==
  sha1: !binary |-
    MGRiNGM5MTVmYzExZjlhMjYyY2VlZmIyYjYyNmIzYzc4NzI3Y2MwNg==
  fingerprint: !binary |-
    MWZjZjQ1MzE2MmY0NzA1NmMxYjI4MzRkN2NkOTZkNmNkZWM3MGJkNQ==
  dependencies:
  - golang
- name: garden-linux
  version: !binary |-
    NDQyNDVkMDZhOWVmODM5YTdlN2MyMWYyYWFmNzVmYTJhMWQxM2M3NA==
  sha1: !binary |-
    ZGI5MmQ1N2M0YTVjMzY3MDRmMTRlNDJjODk2ZGEzMTNlYTY1N2QyOA==
  fingerprint: !binary |-
    NDQyNDVkMDZhOWVmODM5YTdlN2MyMWYyYWFmNzVmYTJhMWQxM2M3NA==
  dependencies:
  - golang
- name: consul_0.4
  version: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  sha1: !binary |-
    YTlmN2IzZmI2MDZmOWQxMjQ5ZTkwODYxZGUyNGQzYjdjMzFkYjM2Mw==
  fingerprint: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  dependencies: []
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    NWIwZmZiYTAxMGIyM2RkMjFlZjIxZTdjMDM4NWQ0NjhhNWRhYTNiMw==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
jobs:
- name: converger
  version: !binary |-
    YTI2YWNmMzM2ZDAwYTAzZDkxZWY2ZjZlYWVlMDI0MTFkMmU3YjQwMQ==
  fingerprint: !binary |-
    YTI2YWNmMzM2ZDAwYTAzZDkxZWY2ZjZlYWVlMDI0MTFkMmU3YjQwMQ==
  sha1: !binary |-
    YTMyOWQzN2ZhNzhlMDg1NTE0ZjE5ODM1NGNmODM5ZjhmNTBhZDMzMA==
- name: smoke-tests
  version: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  fingerprint: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  sha1: !binary |-
    YjQxNDIyZTJmN2I0NjIyMzA5NTdkOWZlZGI5MDk0MDBlNmEzOTllNg==
- name: etcd_metrics_server
  version: !binary |-
    Zjc5ZTk4NDRmZjA2MzM5MmEyZWU3NTBjMTc2ZGE4ZTgyMTI5YmFiYQ==
  fingerprint: !binary |-
    Zjc5ZTk4NDRmZjA2MzM5MmEyZWU3NTBjMTc2ZGE4ZTgyMTI5YmFiYQ==
  sha1: !binary |-
    ZGFkMWZmZTQ4MWY4MjJmYjc4ZmQzYWM3YTRjZjVhNDAyZjE0OTIwOQ==
- name: executor
  version: !binary |-
    NzRlMDQzYmRlZjAzZTBiZmI1MzIyZGQyYzI2NjJjYTFkM2NhNjY0MQ==
  fingerprint: !binary |-
    NzRlMDQzYmRlZjAzZTBiZmI1MzIyZGQyYzI2NjJjYTFkM2NhNjY0MQ==
  sha1: !binary |-
    MzUwNjlkMjJkMDY5NDIwYmI3MDBjMjY2NTAwZmQ2YWE4YTBmZDUyMA==
- name: acceptance-tests
  version: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  fingerprint: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  sha1: !binary |-
    OGExNDljMDI3NzNhOTJlNDEyOTlkM2IxNjYxNjk3OGU1ZGU5ODA4MQ==
- name: receptor
  version: !binary |-
    ZWQyMzQzZTIyOTRhM2JjMGY4NDQxYzRhMWZjMDg3YTE0ZDgzZWQxYQ==
  fingerprint: !binary |-
    ZWQyMzQzZTIyOTRhM2JjMGY4NDQxYzRhMWZjMDg3YTE0ZDgzZWQxYQ==
  sha1: !binary |-
    ZmYzMWNkZjE4NjQyM2UwZmUyNjQzOTQ2MzAxZjM3YmJlZTQ1MDYyYg==
- name: rep
  version: !binary |-
    NmJjNzUxZDhhZDY2NzhkOTdiYmEzNzc3YWI0ZjU4MzQ0ZjEzMDQ1Zg==
  fingerprint: !binary |-
    NmJjNzUxZDhhZDY2NzhkOTdiYmEzNzc3YWI0ZjU4MzQ0ZjEzMDQ1Zg==
  sha1: !binary |-
    MDYwM2U0YjliZDBkNjkwMjU1NjdhMzlkZGU3YzkzZjExMWFiY2QxNg==
- name: etcd
  version: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  fingerprint: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  sha1: !binary |-
    MzFiNDJiOTYwYzBkMWUwMDhkZTE4YmFlNDYxZDI5OTBkZjllNGZjZQ==
- name: file_server
  version: !binary |-
    MjVmNjg4ZjAzNTJkMDY4MWQ2MWYzYzYzM2Q1ZmViODgwYWVmMGQ1Yg==
  fingerprint: !binary |-
    MjVmNjg4ZjAzNTJkMDY4MWQ2MWYzYzYzM2Q1ZmViODgwYWVmMGQ1Yg==
  sha1: !binary |-
    N2Q3NmMxN2NkMmYxODJkZjZhYzI1NjNmN2ZjMjUzZDE4NWM4OWU3Yw==
- name: route_emitter
  version: !binary |-
    MTczMzM2Mzg1ZmU3MTU0OTE4MGM1N2YyYzUwMTliNDRlZTQyOGE0MA==
  fingerprint: !binary |-
    MTczMzM2Mzg1ZmU3MTU0OTE4MGM1N2YyYzUwMTliNDRlZTQyOGE0MA==
  sha1: !binary |-
    Njg3NDUwNjM2NjI3YjgwZGQ4ZjI0Mzg0NWI5ZDEwMzMzYTNlMzQyZA==
- name: tps
  version: !binary |-
    ZmIwYmY3Y2U4OThlMDFkMzhiOTZjMThkOWZhYTBjYmYzMWE0N2FkMA==
  fingerprint: !binary |-
    ZmIwYmY3Y2U4OThlMDFkMzhiOTZjMThkOWZhYTBjYmYzMWE0N2FkMA==
  sha1: !binary |-
    MjYzMjZiNGFmNGM4NmJhNGEzYWNhOTJhMmYwNGRjMzY3ODM5N2E5Nw==
- name: auctioneer
  version: !binary |-
    YzNiYWY4Y2UyNmI4YjE1MTU2YzYzMjU1ZDgyNzE1MDM2YjA1YmNlZQ==
  fingerprint: !binary |-
    YzNiYWY4Y2UyNmI4YjE1MTU2YzYzMjU1ZDgyNzE1MDM2YjA1YmNlZQ==
  sha1: !binary |-
    MGRhMTI5OWJjOWVjNjdlY2Y1ZTc3NmUwNTMzZGJmZDI2OTA0NTc2ZA==
- name: nsync
  version: !binary |-
    MzRkNWI4MzZkNDIyYjljZmZiNjY4OTlkYTAxOTUzMDhmOWM4ZTNlMw==
  fingerprint: !binary |-
    MzRkNWI4MzZkNDIyYjljZmZiNjY4OTlkYTAxOTUzMDhmOWM4ZTNlMw==
  sha1: !binary |-
    OWY5ZWE5OTcwYzM4ZmZkYjBiMmU3MTdjMDc1OGViNGY5MjgwMTQwNQ==
- name: stager
  version: !binary |-
    M2Y5NDRiNGE3YTBjYTdmZDAzMWJkZDkwODg4Mzk0NGI5ZGNiOTRhOQ==
  fingerprint: !binary |-
    M2Y5NDRiNGE3YTBjYTdmZDAzMWJkZDkwODg4Mzk0NGI5ZGNiOTRhOQ==
  sha1: !binary |-
    NmQ5NWQwM2MwYjE0MzEzNTQxZjQ3MmMzZjcwMTE1YzMwMzgyYWNiMA==
- name: runtime_metrics_server
  version: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  fingerprint: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  sha1: !binary |-
    MjFlZDQyOGUwNTEwZDE0YzIwNjg1OGI3YzFjZTFhNTczMDNjOTMyZA==
- name: consul-agent
  version: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  fingerprint: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  sha1: !binary |-
    MDExZWM5ZDgyZjcwMzhlYjY3OTdkNDFiMDUyOGQxNGViNTQ4YmIzZg==
- name: garden-linux
  version: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  fingerprint: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  sha1: !binary |-
    NTdlOWJmZTM5ODVhZWI5MzY5Mjc0MGNhZTg4ZTM5YzM1YWI3YTIwMg==
commit_hash: bbadfc25
uncommitted_changes: true
name: diego
version: '0.660'
