---
packages:
- name: garden-linux
  version: !binary |-
    YjA1ZGRkMmU5ZjkyYzBmMTkyYTI0YTE0N2FjMTcxOTNiNWE1YmNmNA==
  sha1: !binary |-
    OThhMzIzMmM2Nzc4NTg1MjI4M2YyMWJlMDg3NTliMjUzMTg0YzdkZA==
  fingerprint: !binary |-
    YjA1ZGRkMmU5ZjkyYzBmMTkyYTI0YTE0N2FjMTcxOTNiNWE1YmNmNA==
  dependencies:
  - golang
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MTUxMjA2NjY3ZmI0MjQzMTUzYjUwODA2ZTk3YjFmYjdkZTlhOTRjZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: nsync
  version: !binary |-
    NzVkZDFhOThiZDVjZWJkZmI3NDAwYTc3MjM4ZjM2ZjdhYzA3OGVjMQ==
  sha1: !binary |-
    Yjg4NzE3MTU4YWJjZGJhODdiOTU2MDM1NmI5NjI1ZWQ2OGNjYTAzNA==
  fingerprint: !binary |-
    NzVkZDFhOThiZDVjZWJkZmI3NDAwYTc3MjM4ZjM2ZjdhYzA3OGVjMQ==
  dependencies:
  - golang
- name: etcd_metrics_server
  version: !binary |-
    NTQ3NjUxZjUyZWVmMGJlODJmMmY5Yjk3OTg3NzMyYzA0MWQ1Yzk3Nw==
  sha1: !binary |-
    OGY4ZDY3MmZmZWJkYWRmZjJkZDgxOGM5YWEwMjNlMjZhMmU3MTljYw==
  fingerprint: !binary |-
    NTQ3NjUxZjUyZWVmMGJlODJmMmY5Yjk3OTg3NzMyYzA0MWQ1Yzk3Nw==
  dependencies:
  - golang
- name: rep
  version: !binary |-
    YjM2ZDhiOGU5NTUyNDE0NGUwMDc5OWNkYWQ0OTUyZWZmOGFlNTIwYQ==
  sha1: !binary |-
    ZTI1OTg3NGM5ZDU5MmZkZjBjZDAwY2VkY2M3MTAyZDM1Zjk2NjhhMw==
  fingerprint: !binary |-
    YjM2ZDhiOGU5NTUyNDE0NGUwMDc5OWNkYWQ0OTUyZWZmOGFlNTIwYQ==
  dependencies:
  - golang
- name: route_emitter
  version: !binary |-
    Y2NiZDg2MGMxMzMyODNhYmFjZWMzYjZlYjQ1N2ZiOWQ5YzgyZDQxNg==
  sha1: !binary |-
    ZjMyYjE2NjZjNmM0Mzk5YzJlZTE0ZWRhNjBiNGQzMmZhZjAwZTBjMg==
  fingerprint: !binary |-
    Y2NiZDg2MGMxMzMyODNhYmFjZWMzYjZlYjQ1N2ZiOWQ5YzgyZDQxNg==
  dependencies:
  - golang
- name: smoke-tests
  version: !binary |-
    YjhiZDRjOWUyZWM4ZTM5YTIzZTM3YWRhMDRhNWVkMGZhNjU0MjA2YQ==
  sha1: !binary |-
    ZTcxYTA0ZGFkZDU2NWJiY2JmYjNhZTg3OGNkNTZlNDgxZTllMWViMQ==
  fingerprint: !binary |-
    YjhiZDRjOWUyZWM4ZTM5YTIzZTM3YWRhMDRhNWVkMGZhNjU0MjA2YQ==
  dependencies:
  - golang
- name: file_server
  version: !binary |-
    MGUzY2ZhNTE4OGZkMjY4MTVhY2U5NWMwZmViMzk4NGI5MTM2ZmZhMw==
  sha1: !binary |-
    NzIwNTQ2YjJhYTk0MmRkYjAwMTFkYTRmMWUzMzNiMmM0MmU4M2M3ZA==
  fingerprint: !binary |-
    MGUzY2ZhNTE4OGZkMjY4MTVhY2U5NWMwZmViMzk4NGI5MTM2ZmZhMw==
  dependencies:
  - golang
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    MGFhZmI4ZDU0M2M3YTExNDdhYzdkMGFhNmMzMzg1NDQyNjRiNjM1MQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: auctioneer
  version: !binary |-
    Y2M5MDk5YmM2YzQzODEwMGM1ZTM4MzQ4ZDRjMzEzNDI5MTZmMjNmOQ==
  sha1: !binary |-
    YTI4YzA0YjgxODBkNGE5MDQzMDBhMWQwZWQzNTU0NjUwMTQ4Zjg3Yg==
  fingerprint: !binary |-
    Y2M5MDk5YmM2YzQzODEwMGM1ZTM4MzQ4ZDRjMzEzNDI5MTZmMjNmOQ==
  dependencies:
  - golang
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    NWIwZmZiYTAxMGIyM2RkMjFlZjIxZTdjMDM4NWQ0NjhhNWRhYTNiMw==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    ODNlZmQ2ZGE2OGYzMTFhZGFiYzg0OTMxOGU1NjcxMjczODU3YTdjZg==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: tps
  version: !binary |-
    ODViZDAwOGQ2NWI0ZDIwMDQzNmNkNzFkNmNlZDUwNWUwODIyYjQ0ZA==
  sha1: !binary |-
    NTA2ZDM4NzQ4MTFhMGFhZDExNTQ0OWIxMjJjMGY4ZjIzMDM2NTIxYQ==
  fingerprint: !binary |-
    ODViZDAwOGQ2NWI0ZDIwMDQzNmNkNzFkNmNlZDUwNWUwODIyYjQ0ZA==
  dependencies:
  - golang
- name: receptor
  version: !binary |-
    M2U3NzY3N2NjZGNkMDdlZTAyY2JhMWM1ZjAyNmI1NGQwM2I2YmJiZQ==
  sha1: !binary |-
    YzAyMDBhZjk0YTMwNjI2MjM3YTFjY2VmY2E4MWEzM2ZiYzY3MjUyOQ==
  fingerprint: !binary |-
    M2U3NzY3N2NjZGNkMDdlZTAyY2JhMWM1ZjAyNmI1NGQwM2I2YmJiZQ==
  dependencies:
  - golang
- name: etcd
  version: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  sha1: !binary |-
    NjdlMWM4Yjk1YzhiNWMzMmIxZjg5ZjNjMjc1YmQ5ZjYxNmExZDc2Yw==
  fingerprint: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  dependencies:
  - golang
- name: runtime_metrics_server
  version: !binary |-
    YmRhOTQ0YzdhYzI3Y2U1NzE5MjE4MGM4ZGMyMDI2OWY1ZTBhOTU2Ng==
  sha1: !binary |-
    M2ZiZjRmNzIwMGYyNWIxOTUxNGJjM2NmZTIzNmZhOTVlMGM0MDQ5MQ==
  fingerprint: !binary |-
    YmRhOTQ0YzdhYzI3Y2U1NzE5MjE4MGM4ZGMyMDI2OWY1ZTBhOTU2Ng==
  dependencies:
  - golang
- name: consul_0.4
  version: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  sha1: !binary |-
    YTlmN2IzZmI2MDZmOWQxMjQ5ZTkwODYxZGUyNGQzYjdjMzFkYjM2Mw==
  fingerprint: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  dependencies: []
- name: cf-cli
  version: !binary |-
    NjQ1YjY5NTA1MmUzOWJlZGVhNWI3MTdkZDk5MzYwZWY1ZjQ5MmJkZA==
  sha1: !binary |-
    MzQ5MDAxMDdiZWI3NDdlZjQxNjQ1ZTBjYTcxZmE5OTgyNGQwNTgxOQ==
  fingerprint: !binary |-
    NjQ1YjY5NTA1MmUzOWJlZGVhNWI3MTdkZDk5MzYwZWY1ZjQ5MmJkZA==
  dependencies: []
- name: executor
  version: !binary |-
    ZjI5NjhjYTFkMTFhMWY4MDVhNDZkZmM0YTY1ODNkNGRiMTgzYzA2MQ==
  sha1: !binary |-
    ODMxYjMwNzRlNjI3MDYyZjJmYzY3ZGUxNmMzN2NhNzg1NzA4M2QxMw==
  fingerprint: !binary |-
    ZjI5NjhjYTFkMTFhMWY4MDVhNDZkZmM0YTY1ODNkNGRiMTgzYzA2MQ==
  dependencies:
  - golang
- name: acceptance-tests
  version: !binary |-
    ZWM3ZmIwOTQyZTBmZWZmZTE0ZTQ5NjgyMDA3NDFkYjJmYzgyMTMwNw==
  sha1: !binary |-
    NTg2MGU1ZTQ3OTJiYjIwMjBlMzJhMTUwNTZlYWIzMDQwNGZhMjY3YQ==
  fingerprint: !binary |-
    ZWM3ZmIwOTQyZTBmZWZmZTE0ZTQ5NjgyMDA3NDFkYjJmYzgyMTMwNw==
  dependencies:
  - golang
- name: docker-circus
  version: !binary |-
    MGQ5N2QwMjVmOTc4MjRkYzE4YzRjYzkxYTAzZTQyYTdmYjQwOGYxOA==
  sha1: !binary |-
    MzhlMjY3ZDJmNGU3ZjBlZWNiNWU4OGY2OGNhMmU3YzFmMTY5MDc3Zg==
  fingerprint: !binary |-
    MGQ5N2QwMjVmOTc4MjRkYzE4YzRjYzkxYTAzZTQyYTdmYjQwOGYxOA==
  dependencies:
  - golang
- name: linux-circus
  version: !binary |-
    ZGE4NDQ3YzM2ZjdhYWEyNjE5MTRmNWIyNmI3ZjE0MzM0ZDdlYmIwMw==
  sha1: !binary |-
    YzA1OTJlNTQ1YzUzMTE0MTRhMzRmOWM4MDAyOGQyMWM0NzAxMTY0OQ==
  fingerprint: !binary |-
    ZGE4NDQ3YzM2ZjdhYWEyNjE5MTRmNWIyNmI3ZjE0MzM0ZDdlYmIwMw==
  dependencies:
  - golang
- name: stager
  version: !binary |-
    MmU4NGFhZGRiYzFjNzViZTIzNzVmYzgxMThhZTZiMzBlYmNhOTYxOQ==
  sha1: !binary |-
    NTc3ZjNiNWE0NzM2MjY5ZjVmOTdhZDc5MDZjM2Y5NTA4Y2JkMzc5Mg==
  fingerprint: !binary |-
    MmU4NGFhZGRiYzFjNzViZTIzNzVmYzgxMThhZTZiMzBlYmNhOTYxOQ==
  dependencies:
  - golang
- name: rootfs_lucid64
  version: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  sha1: !binary |-
    NGUyOTNiNWQwMjBkNmRiZGVhN2FmMjZhYmUzZTRmMDg2NGJjNjFmMg==
  fingerprint: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  dependencies: []
- name: converger
  version: !binary |-
    OTQyOTE4OWYwMjYwYWQwMDZjMTIxMmI3NWU4Y2M4MzlkMWY3ZWU3MQ==
  sha1: !binary |-
    YzZjYmQwNTcwMzc0YTc0YjE3YWYzMTI2NDkzZDA3NjkwY2YxY2M4Yg==
  fingerprint: !binary |-
    OTQyOTE4OWYwMjYwYWQwMDZjMTIxMmI3NWU4Y2M4MzlkMWY3ZWU3MQ==
  dependencies:
  - golang
jobs:
- name: garden-linux
  version: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  fingerprint: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  sha1: !binary |-
    NTdlOWJmZTM5ODVhZWI5MzY5Mjc0MGNhZTg4ZTM5YzM1YWI3YTIwMg==
- name: nsync
  version: !binary |-
    OTFkNmZmNzU4ZTUwMzVhYTViYjAxOWZlNTgzNTgwN2VmMWY1OWE4MQ==
  fingerprint: !binary |-
    OTFkNmZmNzU4ZTUwMzVhYTViYjAxOWZlNTgzNTgwN2VmMWY1OWE4MQ==
  sha1: !binary |-
    YjVkZTgxZjNlYWQxODUwNWExZTg0NzllNzk3NGU2YTY1NTMwMzMwMA==
- name: etcd_metrics_server
  version: !binary |-
    Zjc5ZTk4NDRmZjA2MzM5MmEyZWU3NTBjMTc2ZGE4ZTgyMTI5YmFiYQ==
  fingerprint: !binary |-
    Zjc5ZTk4NDRmZjA2MzM5MmEyZWU3NTBjMTc2ZGE4ZTgyMTI5YmFiYQ==
  sha1: !binary |-
    ZGFkMWZmZTQ4MWY4MjJmYjc4ZmQzYWM3YTRjZjVhNDAyZjE0OTIwOQ==
- name: consul-agent
  version: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  fingerprint: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  sha1: !binary |-
    MDExZWM5ZDgyZjcwMzhlYjY3OTdkNDFiMDUyOGQxNGViNTQ4YmIzZg==
- name: rep
  version: !binary |-
    ZTBhMTZlNzViOWRmODU1ZjVlOThhNjBkZWI3YjhjY2Q3YzRjZTU4YQ==
  fingerprint: !binary |-
    ZTBhMTZlNzViOWRmODU1ZjVlOThhNjBkZWI3YjhjY2Q3YzRjZTU4YQ==
  sha1: !binary |-
    YzhjMjU1YjY4YWM5YzQyYmIwZjAyYTVjNTg1OGUyMDE0YjRiNTJiZg==
- name: route_emitter
  version: !binary |-
    MTczMzM2Mzg1ZmU3MTU0OTE4MGM1N2YyYzUwMTliNDRlZTQyOGE0MA==
  fingerprint: !binary |-
    MTczMzM2Mzg1ZmU3MTU0OTE4MGM1N2YyYzUwMTliNDRlZTQyOGE0MA==
  sha1: !binary |-
    Njg3NDUwNjM2NjI3YjgwZGQ4ZjI0Mzg0NWI5ZDEwMzMzYTNlMzQyZA==
- name: smoke-tests
  version: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  fingerprint: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  sha1: !binary |-
    YjQxNDIyZTJmN2I0NjIyMzA5NTdkOWZlZGI5MDk0MDBlNmEzOTllNg==
- name: file_server
  version: !binary |-
    MjVmNjg4ZjAzNTJkMDY4MWQ2MWYzYzYzM2Q1ZmViODgwYWVmMGQ1Yg==
  fingerprint: !binary |-
    MjVmNjg4ZjAzNTJkMDY4MWQ2MWYzYzYzM2Q1ZmViODgwYWVmMGQ1Yg==
  sha1: !binary |-
    N2Q3NmMxN2NkMmYxODJkZjZhYzI1NjNmN2ZjMjUzZDE4NWM4OWU3Yw==
- name: auctioneer
  version: !binary |-
    ODBmNmI2MWNmMDVjMGNmZGQ0MjY3OGI4NjI3ZDRiM2MwNTNlOTY4ZQ==
  fingerprint: !binary |-
    ODBmNmI2MWNmMDVjMGNmZGQ0MjY3OGI4NjI3ZDRiM2MwNTNlOTY4ZQ==
  sha1: !binary |-
    MTJhMDg3MDgzZGZkMDVjYmI4Y2I3YjY3MGQyNDRhYzhiZWQzYmQwOA==
- name: tps
  version: !binary |-
    ZmEzNGRjODA4YWViM2Q0NWFmOWFhNGJiNmI4Y2JkMzI2OThkMzgyMQ==
  fingerprint: !binary |-
    ZmEzNGRjODA4YWViM2Q0NWFmOWFhNGJiNmI4Y2JkMzI2OThkMzgyMQ==
  sha1: !binary |-
    YzE1N2Y0NzVmMTk3MmU3NTRhMzk2N2MxODU1OTk2ZjYyZWM0MmM0MQ==
- name: receptor
  version: !binary |-
    MzBmZGM4NTdkZjEzYTM3ZjFiZTljMDVlNDg5YTI4NGY5OGUxYTUyZA==
  fingerprint: !binary |-
    MzBmZGM4NTdkZjEzYTM3ZjFiZTljMDVlNDg5YTI4NGY5OGUxYTUyZA==
  sha1: !binary |-
    YWQzMDRhYWRhYTE4YzRjOTg5YzcwYWI5MmYyNjc3MDE4YzhlZjE3MA==
- name: etcd
  version: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  fingerprint: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  sha1: !binary |-
    MzFiNDJiOTYwYzBkMWUwMDhkZTE4YmFlNDYxZDI5OTBkZjllNGZjZQ==
- name: runtime_metrics_server
  version: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  fingerprint: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  sha1: !binary |-
    MjFlZDQyOGUwNTEwZDE0YzIwNjg1OGI3YzFjZTFhNTczMDNjOTMyZA==
- name: executor
  version: !binary |-
    ZThkM2NkMGIwM2E3ZTdkYTE2MTEzYjUxMjAzZTg1YWNhOWQzNjYyNQ==
  fingerprint: !binary |-
    ZThkM2NkMGIwM2E3ZTdkYTE2MTEzYjUxMjAzZTg1YWNhOWQzNjYyNQ==
  sha1: !binary |-
    YWVmZGRmOGU3YmY4YTQ0MmFkNTA1MTVmNTM0ZGUzN2QzOTdmYzZmMg==
- name: acceptance-tests
  version: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  fingerprint: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  sha1: !binary |-
    OGExNDljMDI3NzNhOTJlNDEyOTlkM2IxNjYxNjk3OGU1ZGU5ODA4MQ==
- name: stager
  version: !binary |-
    ZjZjZWY3ZTQwNmViOWRlZDMzMjA0MTRmOWJjZjdlNmQxNThjZmNiZQ==
  fingerprint: !binary |-
    ZjZjZWY3ZTQwNmViOWRlZDMzMjA0MTRmOWJjZjdlNmQxNThjZmNiZQ==
  sha1: !binary |-
    ZDlhN2VlMDhlYzk4N2I1ZDk0YjAzY2UxYmNiMTI1Y2M3OTYwY2RjMA==
- name: converger
  version: !binary |-
    YTI2YWNmMzM2ZDAwYTAzZDkxZWY2ZjZlYWVlMDI0MTFkMmU3YjQwMQ==
  fingerprint: !binary |-
    YTI2YWNmMzM2ZDAwYTAzZDkxZWY2ZjZlYWVlMDI0MTFkMmU3YjQwMQ==
  sha1: !binary |-
    YTMyOWQzN2ZhNzhlMDg1NTE0ZjE5ODM1NGNmODM5ZjhmNTBhZDMzMA==
commit_hash: c998a15c
uncommitted_changes: true
name: diego
version: '0.581'
