---
packages:
- name: auctioneer
  version: !binary |-
    NGFlMDAxNmM2MDU1NDgzMTQwODMzMTU3MjQ1OTkyOTJkMzE5MTlhMA==
  sha1: !binary |-
    ZTAyZDg2Mzk1N2Q0MDI1ZWMwZWQ2ZmJmMGMzZmNkZTU5YTU1NjRiYw==
  fingerprint: !binary |-
    NGFlMDAxNmM2MDU1NDgzMTQwODMzMTU3MjQ1OTkyOTJkMzE5MTlhMA==
  dependencies:
  - golang
- name: nsync
  version: !binary |-
    Nzk5OTRhNjFlODU3ZTA1OWFlZjIxMjk1ODMwZDMwMGI1YTFjOTJjYQ==
  sha1: !binary |-
    NTkwNjIzN2M5ODQ3YzRiMWQ5ZjIxYTg2NjVjNTZjZjM0NDgzODNhOQ==
  fingerprint: !binary |-
    Nzk5OTRhNjFlODU3ZTA1OWFlZjIxMjk1ODMwZDMwMGI1YTFjOTJjYQ==
  dependencies:
  - golang
- name: receptor
  version: !binary |-
    YzMwZjRjZTRmZWJjZTNlMTk3ZmQ0NDE5MzM0ZTc0NzQyMDgzZTBmYQ==
  sha1: !binary |-
    ZTgwM2MxNWExNjQ3ZDRiNTk4MzFiZWUyOTUyNjFhNTdmNTMxN2Q4ZQ==
  fingerprint: !binary |-
    YzMwZjRjZTRmZWJjZTNlMTk3ZmQ0NDE5MzM0ZTc0NzQyMDgzZTBmYQ==
  dependencies:
  - golang
- name: garden-linux
  version: !binary |-
    NDQyNDVkMDZhOWVmODM5YTdlN2MyMWYyYWFmNzVmYTJhMWQxM2M3NA==
  sha1: !binary |-
    ZGI5MmQ1N2M0YTVjMzY3MDRmMTRlNDJjODk2ZGEzMTNlYTY1N2QyOA==
  fingerprint: !binary |-
    NDQyNDVkMDZhOWVmODM5YTdlN2MyMWYyYWFmNzVmYTJhMWQxM2M3NA==
  dependencies:
  - golang
- name: linux-circus
  version: !binary |-
    YTAwNTJiYzM1OGMzNTlkMzFjZmFiMGM0ODk3NjkxOGNkMjJkZDM2Mw==
  sha1: !binary |-
    YmM5ZWM1OTQyMmZjZDYyNWRkOGNiOTg3MTNlNjBjZjE2MDc3MDE1Mg==
  fingerprint: !binary |-
    YTAwNTJiYzM1OGMzNTlkMzFjZmFiMGM0ODk3NjkxOGNkMjJkZDM2Mw==
  dependencies:
  - golang
- name: executor
  version: !binary |-
    Y2Q4MjY5ZmE1OGNkZGJmZTNhNjNjODkwNjE5NDc3MDNmYWVkYjc4Yg==
  sha1: !binary |-
    NDFiN2U4YWNlNDQ2ZTk1YTE0MDZjOWRkMDhhY2ZmNTM2Y2JkOTM4Mw==
  fingerprint: !binary |-
    Y2Q4MjY5ZmE1OGNkZGJmZTNhNjNjODkwNjE5NDc3MDNmYWVkYjc4Yg==
  dependencies:
  - golang
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    ODNlZmQ2ZGE2OGYzMTFhZGFiYzg0OTMxOGU1NjcxMjczODU3YTdjZg==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: cf-cli
  version: !binary |-
    NjQ1YjY5NTA1MmUzOWJlZGVhNWI3MTdkZDk5MzYwZWY1ZjQ5MmJkZA==
  sha1: !binary |-
    MzQ5MDAxMDdiZWI3NDdlZjQxNjQ1ZTBjYTcxZmE5OTgyNGQwNTgxOQ==
  fingerprint: !binary |-
    NjQ1YjY5NTA1MmUzOWJlZGVhNWI3MTdkZDk5MzYwZWY1ZjQ5MmJkZA==
  dependencies: []
- name: rep
  version: !binary |-
    NGUxZDBlNGZiYjU4YWJmYjlmMTZhMzA3Y2Q2MjQ2YTk0N2UxNmMwYg==
  sha1: !binary |-
    YThiNjQyYmJlZjhiNDM2NWU3YTAxMTRlOTY4ZDRmNjExOTI5ZjQ1ZQ==
  fingerprint: !binary |-
    NGUxZDBlNGZiYjU4YWJmYjlmMTZhMzA3Y2Q2MjQ2YTk0N2UxNmMwYg==
  dependencies:
  - golang
- name: stager
  version: !binary |-
    M2ZmMTU3MjFkNTc4M2RmMWE0OTMxODc5ZDVkMzQxNmQ0ZGE4NzAwMw==
  sha1: !binary |-
    ZGMwYzk0YTVkNWYxZDUwNGY1YTE5ZDE4N2QzNWU1MjNlZTk0Y2JlMg==
  fingerprint: !binary |-
    M2ZmMTU3MjFkNTc4M2RmMWE0OTMxODc5ZDVkMzQxNmQ0ZGE4NzAwMw==
  dependencies:
  - golang
- name: converger
  version: !binary |-
    ZGI5NWE3Nzk3ZWM1NzgwMGZiNzc4NWUzYWEzNjNhNjM4ODQ4YTYwZg==
  sha1: !binary |-
    ZTM2YTBmN2QxMDM3YjljOTU0ZTNhM2U2ODViODQxMDQwZjQ4YjM2NQ==
  fingerprint: !binary |-
    ZGI5NWE3Nzk3ZWM1NzgwMGZiNzc4NWUzYWEzNjNhNjM4ODQ4YTYwZg==
  dependencies:
  - golang
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    MGFhZmI4ZDU0M2M3YTExNDdhYzdkMGFhNmMzMzg1NDQyNjRiNjM1MQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: smoke-tests
  version: !binary |-
    ZGZiZjU4OGEzZGY0YzJlNGUzNjgyN2Y1MTA1NWMwNjE4MTc1YTI2Nw==
  sha1: !binary |-
    ZTFiYzg5ZjJhZDRjMmJjMjJkZWE5MzMzMzQ5NWE5MTU5YWJmODFmMw==
  fingerprint: !binary |-
    ZGZiZjU4OGEzZGY0YzJlNGUzNjgyN2Y1MTA1NWMwNjE4MTc1YTI2Nw==
  dependencies:
  - golang
- name: rootfs_lucid64
  version: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  sha1: !binary |-
    NGUyOTNiNWQwMjBkNmRiZGVhN2FmMjZhYmUzZTRmMDg2NGJjNjFmMg==
  fingerprint: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  dependencies: []
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    NWIwZmZiYTAxMGIyM2RkMjFlZjIxZTdjMDM4NWQ0NjhhNWRhYTNiMw==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
- name: route_emitter
  version: !binary |-
    Y2MyMTg0NTE4ZjU0ZWFhYzEzY2Y3ODBhN2JlNjU2MTgyZjAyMTJjMw==
  sha1: !binary |-
    NmJkODg0ZjA1OGQ5NTZjZmQ5N2E0ZmQ1NjExZTg0M2FmOTZkMDA1YQ==
  fingerprint: !binary |-
    Y2MyMTg0NTE4ZjU0ZWFhYzEzY2Y3ODBhN2JlNjU2MTgyZjAyMTJjMw==
  dependencies:
  - golang
- name: acceptance-tests
  version: !binary |-
    YWNlNzY4NTE5OGNiZmJlYjQ3OWY5MGI1NDlhOWIyNjg1NzllYTVmNA==
  sha1: !binary |-
    N2IxNjZlMWNmNmNhN2M3ZWZmZTFkODVmOTNhYjlmZWQ1YThjYjYxYw==
  fingerprint: !binary |-
    YWNlNzY4NTE5OGNiZmJlYjQ3OWY5MGI1NDlhOWIyNjg1NzllYTVmNA==
  dependencies:
  - golang
- name: file_server
  version: !binary |-
    MTFlZTlkYjVkYWFlZTk0NGRlNWRiOGVlYTA3ZTc2MzM0NDdhM2JjMg==
  sha1: !binary |-
    MjIzOTc5YzE1NTRhMjhmODQwOTFhZDhlMTNlMzg3NDQ5MmRmMTNmOQ==
  fingerprint: !binary |-
    MTFlZTlkYjVkYWFlZTk0NGRlNWRiOGVlYTA3ZTc2MzM0NDdhM2JjMg==
  dependencies:
  - golang
- name: consul_0.4
  version: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  sha1: !binary |-
    YTlmN2IzZmI2MDZmOWQxMjQ5ZTkwODYxZGUyNGQzYjdjMzFkYjM2Mw==
  fingerprint: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  dependencies: []
- name: runtime_metrics_server
  version: !binary |-
    ODVkZjdiZjU2ZjBiOTYyMDI4Y2Q1ODdkNjY4ZjVhOWUxOTIwMWZhNQ==
  sha1: !binary |-
    NmZlMTk5MzY2ZTcxYmI0YTUxZjk0ZjY2Nzc0NTEwMjJjNzk1MDg1OA==
  fingerprint: !binary |-
    ODVkZjdiZjU2ZjBiOTYyMDI4Y2Q1ODdkNjY4ZjVhOWUxOTIwMWZhNQ==
  dependencies:
  - golang
- name: etcd_metrics_server
  version: !binary |-
    MDgzZjA0NGU4MmQ3YzAxY2UyZDcyZDg0MzFlMTJkNWQyNjBhNjY2OQ==
  sha1: !binary |-
    NzE1ZTMxYjUxNTdlYTIzYmM1YTQxNDQ2ZTllNTliMDM4NTYwZjExNA==
  fingerprint: !binary |-
    MDgzZjA0NGU4MmQ3YzAxY2UyZDcyZDg0MzFlMTJkNWQyNjBhNjY2OQ==
  dependencies:
  - golang
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MTUxMjA2NjY3ZmI0MjQzMTUzYjUwODA2ZTk3YjFmYjdkZTlhOTRjZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: tps
  version: !binary |-
    MGNkMjNjNTA1NjAzYTQzZmI0Y2ZjNGU4ZTMyYzY5NDUxZWMxNTc3Mg==
  sha1: !binary |-
    Yzc3Y2MxYWFjYTQwNjU0ZjU2NTI4ZDE3OWRmNGNhMmQ2MDJiNTk5Zg==
  fingerprint: !binary |-
    MGNkMjNjNTA1NjAzYTQzZmI0Y2ZjNGU4ZTMyYzY5NDUxZWMxNTc3Mg==
  dependencies:
  - golang
- name: docker-circus
  version: !binary |-
    NDFhYjJkNmUwM2RlMWJlYjkzMWZkMDA5YzNmMWIzNjhlYjMzODcxMg==
  sha1: !binary |-
    ZmMxNjRjYzBjZDg0YzE1YTM4MDIyNDljODFhZGQ2NGZhZGY4OGU0Yw==
  fingerprint: !binary |-
    NDFhYjJkNmUwM2RlMWJlYjkzMWZkMDA5YzNmMWIzNjhlYjMzODcxMg==
  dependencies:
  - golang
- name: etcd
  version: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  sha1: !binary |-
    NjdlMWM4Yjk1YzhiNWMzMmIxZjg5ZjNjMjc1YmQ5ZjYxNmExZDc2Yw==
  fingerprint: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  dependencies:
  - golang
jobs:
- name: auctioneer
  version: !binary |-
    YzNiYWY4Y2UyNmI4YjE1MTU2YzYzMjU1ZDgyNzE1MDM2YjA1YmNlZQ==
  fingerprint: !binary |-
    YzNiYWY4Y2UyNmI4YjE1MTU2YzYzMjU1ZDgyNzE1MDM2YjA1YmNlZQ==
  sha1: !binary |-
    MGRhMTI5OWJjOWVjNjdlY2Y1ZTc3NmUwNTMzZGJmZDI2OTA0NTc2ZA==
- name: nsync
  version: !binary |-
    MzRkNWI4MzZkNDIyYjljZmZiNjY4OTlkYTAxOTUzMDhmOWM4ZTNlMw==
  fingerprint: !binary |-
    MzRkNWI4MzZkNDIyYjljZmZiNjY4OTlkYTAxOTUzMDhmOWM4ZTNlMw==
  sha1: !binary |-
    OWY5ZWE5OTcwYzM4ZmZkYjBiMmU3MTdjMDc1OGViNGY5MjgwMTQwNQ==
- name: receptor
  version: !binary |-
    ZWQyMzQzZTIyOTRhM2JjMGY4NDQxYzRhMWZjMDg3YTE0ZDgzZWQxYQ==
  fingerprint: !binary |-
    ZWQyMzQzZTIyOTRhM2JjMGY4NDQxYzRhMWZjMDg3YTE0ZDgzZWQxYQ==
  sha1: !binary |-
    ZmYzMWNkZjE4NjQyM2UwZmUyNjQzOTQ2MzAxZjM3YmJlZTQ1MDYyYg==
- name: garden-linux
  version: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  fingerprint: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  sha1: !binary |-
    NTdlOWJmZTM5ODVhZWI5MzY5Mjc0MGNhZTg4ZTM5YzM1YWI3YTIwMg==
- name: executor
  version: !binary |-
    NzRlMDQzYmRlZjAzZTBiZmI1MzIyZGQyYzI2NjJjYTFkM2NhNjY0MQ==
  fingerprint: !binary |-
    NzRlMDQzYmRlZjAzZTBiZmI1MzIyZGQyYzI2NjJjYTFkM2NhNjY0MQ==
  sha1: !binary |-
    MzUwNjlkMjJkMDY5NDIwYmI3MDBjMjY2NTAwZmQ2YWE4YTBmZDUyMA==
- name: rep
  version: !binary |-
    NmJjNzUxZDhhZDY2NzhkOTdiYmEzNzc3YWI0ZjU4MzQ0ZjEzMDQ1Zg==
  fingerprint: !binary |-
    NmJjNzUxZDhhZDY2NzhkOTdiYmEzNzc3YWI0ZjU4MzQ0ZjEzMDQ1Zg==
  sha1: !binary |-
    MDYwM2U0YjliZDBkNjkwMjU1NjdhMzlkZGU3YzkzZjExMWFiY2QxNg==
- name: stager
  version: !binary |-
    M2Y5NDRiNGE3YTBjYTdmZDAzMWJkZDkwODg4Mzk0NGI5ZGNiOTRhOQ==
  fingerprint: !binary |-
    M2Y5NDRiNGE3YTBjYTdmZDAzMWJkZDkwODg4Mzk0NGI5ZGNiOTRhOQ==
  sha1: !binary |-
    NmQ5NWQwM2MwYjE0MzEzNTQxZjQ3MmMzZjcwMTE1YzMwMzgyYWNiMA==
- name: converger
  version: !binary |-
    YTI2YWNmMzM2ZDAwYTAzZDkxZWY2ZjZlYWVlMDI0MTFkMmU3YjQwMQ==
  fingerprint: !binary |-
    YTI2YWNmMzM2ZDAwYTAzZDkxZWY2ZjZlYWVlMDI0MTFkMmU3YjQwMQ==
  sha1: !binary |-
    YTMyOWQzN2ZhNzhlMDg1NTE0ZjE5ODM1NGNmODM5ZjhmNTBhZDMzMA==
- name: smoke-tests
  version: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  fingerprint: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  sha1: !binary |-
    YjQxNDIyZTJmN2I0NjIyMzA5NTdkOWZlZGI5MDk0MDBlNmEzOTllNg==
- name: route_emitter
  version: !binary |-
    MTczMzM2Mzg1ZmU3MTU0OTE4MGM1N2YyYzUwMTliNDRlZTQyOGE0MA==
  fingerprint: !binary |-
    MTczMzM2Mzg1ZmU3MTU0OTE4MGM1N2YyYzUwMTliNDRlZTQyOGE0MA==
  sha1: !binary |-
    Njg3NDUwNjM2NjI3YjgwZGQ4ZjI0Mzg0NWI5ZDEwMzMzYTNlMzQyZA==
- name: acceptance-tests
  version: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  fingerprint: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  sha1: !binary |-
    OGExNDljMDI3NzNhOTJlNDEyOTlkM2IxNjYxNjk3OGU1ZGU5ODA4MQ==
- name: file_server
  version: !binary |-
    MjVmNjg4ZjAzNTJkMDY4MWQ2MWYzYzYzM2Q1ZmViODgwYWVmMGQ1Yg==
  fingerprint: !binary |-
    MjVmNjg4ZjAzNTJkMDY4MWQ2MWYzYzYzM2Q1ZmViODgwYWVmMGQ1Yg==
  sha1: !binary |-
    N2Q3NmMxN2NkMmYxODJkZjZhYzI1NjNmN2ZjMjUzZDE4NWM4OWU3Yw==
- name: runtime_metrics_server
  version: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  fingerprint: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  sha1: !binary |-
    MjFlZDQyOGUwNTEwZDE0YzIwNjg1OGI3YzFjZTFhNTczMDNjOTMyZA==
- name: etcd_metrics_server
  version: !binary |-
    Zjc5ZTk4NDRmZjA2MzM5MmEyZWU3NTBjMTc2ZGE4ZTgyMTI5YmFiYQ==
  fingerprint: !binary |-
    Zjc5ZTk4NDRmZjA2MzM5MmEyZWU3NTBjMTc2ZGE4ZTgyMTI5YmFiYQ==
  sha1: !binary |-
    ZGFkMWZmZTQ4MWY4MjJmYjc4ZmQzYWM3YTRjZjVhNDAyZjE0OTIwOQ==
- name: tps
  version: !binary |-
    ZmIwYmY3Y2U4OThlMDFkMzhiOTZjMThkOWZhYTBjYmYzMWE0N2FkMA==
  fingerprint: !binary |-
    ZmIwYmY3Y2U4OThlMDFkMzhiOTZjMThkOWZhYTBjYmYzMWE0N2FkMA==
  sha1: !binary |-
    MjYzMjZiNGFmNGM4NmJhNGEzYWNhOTJhMmYwNGRjMzY3ODM5N2E5Nw==
- name: consul-agent
  version: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  fingerprint: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  sha1: !binary |-
    MDExZWM5ZDgyZjcwMzhlYjY3OTdkNDFiMDUyOGQxNGViNTQ4YmIzZg==
- name: etcd
  version: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  fingerprint: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  sha1: !binary |-
    MzFiNDJiOTYwYzBkMWUwMDhkZTE4YmFlNDYxZDI5OTBkZjllNGZjZQ==
commit_hash: f16abc33
uncommitted_changes: true
name: diego
version: '0.662'
