---
packages:
- name: consul_0.4
  version: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  sha1: !binary |-
    YTlmN2IzZmI2MDZmOWQxMjQ5ZTkwODYxZGUyNGQzYjdjMzFkYjM2Mw==
  fingerprint: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  dependencies: []
- name: route_emitter
  version: !binary |-
    MDcxN2ZkODk3ZDlhYTMwNGQyZjg4ZmQ1ZGQ0ODlhMGE5NjE0YmJkNw==
  sha1: !binary |-
    ZDU0MWJkN2Q4NmE1NTIzOGYzYzgyYWI1MmI3MWY5YjFkMTBiODdiMg==
  fingerprint: !binary |-
    MDcxN2ZkODk3ZDlhYTMwNGQyZjg4ZmQ1ZGQ0ODlhMGE5NjE0YmJkNw==
  dependencies:
  - golang_1.4
- name: etcd_metrics_server
  version: !binary |-
    NjYwYzEwNDk4MGYyMTk1NjI2NzQyYmVmMTg0ZTgwYmYzZGJkNTQ1ZQ==
  sha1: !binary |-
    MjNhN2IyNWM1OTI1ZjQ0NzgwNTgxMjU2MDVkNzAyZTIzOWM4ODdjMA==
  fingerprint: !binary |-
    NjYwYzEwNDk4MGYyMTk1NjI2NzQyYmVmMTg0ZTgwYmYzZGJkNTQ1ZQ==
  dependencies:
  - golang_1.4
- name: runtime_metrics_server
  version: !binary |-
    OWY4ZDE0Nzc2ZGQwYWRmMjU3MGM5Y2JmYWRjZjExYzFmYmQ1ZTViNw==
  sha1: !binary |-
    MmVlNThiYjE4NmIyZDcxNGQ4N2JlNWI1NTFiYzBkODU2YjY5NjBmMQ==
  fingerprint: !binary |-
    OWY4ZDE0Nzc2ZGQwYWRmMjU3MGM5Y2JmYWRjZjExYzFmYmQ1ZTViNw==
  dependencies:
  - golang_1.4
- name: executor
  version: !binary |-
    ZDRhYjE5MDZmZjBjZDU5M2IwNjI2MWIyYzA5YTBhZGYxYzdiODc2ZQ==
  sha1: !binary |-
    N2NkNGY3MTgyZmMzN2I4NjBjZGY0YTM4ZTMyOTdjYjkxMTI5YjIwMw==
  fingerprint: !binary |-
    ZDRhYjE5MDZmZjBjZDU5M2IwNjI2MWIyYzA5YTBhZGYxYzdiODc2ZQ==
  dependencies:
  - golang_1.4
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    ODNlZmQ2ZGE2OGYzMTFhZGFiYzg0OTMxOGU1NjcxMjczODU3YTdjZg==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: converger
  version: !binary |-
    ZjE4M2FlN2VmYjcyNDA2NWZkOThlZjdkNzhhYTMyN2NmYjRlNTNhNA==
  sha1: !binary |-
    ZGNhMmY4NDk3OGEwYTAxMWRmZGZmNjlmYzcyOGU0NTZiMDVkMWI3NQ==
  fingerprint: !binary |-
    ZjE4M2FlN2VmYjcyNDA2NWZkOThlZjdkNzhhYTMyN2NmYjRlNTNhNA==
  dependencies:
  - golang_1.4
- name: tps
  version: !binary |-
    YTkyMDU1NDY4MjAzZDg4NjVkOGQ3NmE4ZmU4MTM4N2NhZmJhOGQwMA==
  sha1: !binary |-
    MjcxNDFjM2RhODRjOTI2NzE4YjE4NTJiYmIxYzk2MmM5ZTgwZjZiZg==
  fingerprint: !binary |-
    YTkyMDU1NDY4MjAzZDg4NjVkOGQ3NmE4ZmU4MTM4N2NhZmJhOGQwMA==
  dependencies:
  - golang_1.4
- name: etcd
  version: !binary |-
    YjNiZWZhOTNjZWJmNGI1NWRkYjVjNjA5Njk1YjM0ZGI4ZTYzMDQ5NQ==
  sha1: !binary |-
    ZTMzMWE3Y2QwZjM5NjRjZmJhOTQxZGU2MTMwMzdmYjQyZGY4YzljYg==
  fingerprint: !binary |-
    YjNiZWZhOTNjZWJmNGI1NWRkYjVjNjA5Njk1YjM0ZGI4ZTYzMDQ5NQ==
  dependencies:
  - golang_1.4
- name: acceptance-tests
  version: !binary |-
    ZGZlOGMyMjk0NDM2ZmE0YTVmNGVlYjFjZjA3YzAyNjc1ZTI4ODczYg==
  sha1: !binary |-
    YTJiMmU1NWRjNDAwY2I3YmNhZmUwYmUyODQ0ZTFkZWFlYjcyMTQ4YQ==
  fingerprint: !binary |-
    ZGZlOGMyMjk0NDM2ZmE0YTVmNGVlYjFjZjA3YzAyNjc1ZTI4ODczYg==
  dependencies:
  - golang_1.4
- name: linux-circus
  version: !binary |-
    Njg1YWViMmY5ODRmYzZkNDFkOTIxNmU3YjU2ZDVmNGYyMGE1Y2IzZA==
  sha1: !binary |-
    NmM3MjBmZWFkYTBhYjI0ZDExMzQ0OWE4MGQwZGFkYjYyNDEwN2ZjMQ==
  fingerprint: !binary |-
    Njg1YWViMmY5ODRmYzZkNDFkOTIxNmU3YjU2ZDVmNGYyMGE1Y2IzZA==
  dependencies:
  - golang_1.4
- name: rep
  version: !binary |-
    ZTYzNmNhZTRjY2QyZDJkYWIyMTg4MWU1NjQ5ZWI4Yzk2ZjM1ZTY4NA==
  sha1: !binary |-
    MjNiNDBkZGE2OWFmNTVmNGVjOGYyMDkxNmE1OWRjYjhhMDQ1NDQ4Ng==
  fingerprint: !binary |-
    ZTYzNmNhZTRjY2QyZDJkYWIyMTg4MWU1NjQ5ZWI4Yzk2ZjM1ZTY4NA==
  dependencies:
  - golang_1.4
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MTUxMjA2NjY3ZmI0MjQzMTUzYjUwODA2ZTk3YjFmYjdkZTlhOTRjZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    NWIwZmZiYTAxMGIyM2RkMjFlZjIxZTdjMDM4NWQ0NjhhNWRhYTNiMw==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
- name: receptor
  version: !binary |-
    ZTc1OTE1YThkNTQ1NWE4ZGQ1MDljZWJiYmJjMzMxOTk2NjM2MGU2Ng==
  sha1: !binary |-
    MTU2YzRiNmU4YmM2NmIyNWQzMjYwZDQ4YWZmZTNjNjViNDg5MTFmNw==
  fingerprint: !binary |-
    ZTc1OTE1YThkNTQ1NWE4ZGQ1MDljZWJiYmJjMzMxOTk2NjM2MGU2Ng==
  dependencies:
  - golang_1.4
- name: file_server
  version: !binary |-
    YzhhMjdhNGZjOTM4YTk4YWYwNWFiYTk1YmY4MDliMjM5NDdmYjY4Mw==
  sha1: !binary |-
    ZWNlYWYzMTIyNjNhYmJmMmM2ZWVjMzdlNDMzZGMzYWVkNzljN2FkOQ==
  fingerprint: !binary |-
    YzhhMjdhNGZjOTM4YTk4YWYwNWFiYTk1YmY4MDliMjM5NDdmYjY4Mw==
  dependencies:
  - golang_1.4
- name: cf-cli
  version: !binary |-
    ZmZlYmIwMmUzMTcyMjc4MDc5NTI3MjY1MmNhYTY4ZDNjNGJkZDQ5NA==
  sha1: !binary |-
    MGZiYjZlNmY0Nzg4ZGFhMjZhZjg1YTQxYjE0NjkzMmIzODFiOTM1OA==
  fingerprint: !binary |-
    ZmZlYmIwMmUzMTcyMjc4MDc5NTI3MjY1MmNhYTY4ZDNjNGJkZDQ5NA==
  dependencies: []
- name: garden-linux
  version: !binary |-
    OGNkYWFjMGZlODk3ZDk3OTVjZDRmN2E5ZjMzY2I4OGZjY2M2MjI5ZQ==
  sha1: !binary |-
    NmU1ZWEyYmYwZGU0ZGY1YjIzZTQzNTUxYjNkYmI5ODUxZWNlYWU0OQ==
  fingerprint: !binary |-
    OGNkYWFjMGZlODk3ZDk3OTVjZDRmN2E5ZjMzY2I4OGZjY2M2MjI5ZQ==
  dependencies:
  - golang_1.4
- name: golang_1.4
  version: !binary |-
    ODBmZDEwYWFjYTdmYWZhZGE2ZTdmMjI4ZjAzYzUwMjRmYWEwYjUxYQ==
  sha1: !binary |-
    ZjA5NTMzNGE4N2Q2NmRmOTc0YjA5YzcwMjFlYWQ1MTkxM2E4NjMwNQ==
  fingerprint: !binary |-
    ODBmZDEwYWFjYTdmYWZhZGE2ZTdmMjI4ZjAzYzUwMjRmYWEwYjUxYQ==
  dependencies: []
- name: stager
  version: !binary |-
    MTc3NmIzMDc4YmRhYmFhYTlkOGM1MmUwM2UzNzA1MWZmNmZmZThhYQ==
  sha1: !binary |-
    M2RkYjhkMGY3ZTUzOGUxMWNmNTBmOTQ4MzgwN2U2MTIwMzY5NGJjZA==
  fingerprint: !binary |-
    MTc3NmIzMDc4YmRhYmFhYTlkOGM1MmUwM2UzNzA1MWZmNmZmZThhYQ==
  dependencies:
  - golang_1.4
- name: nsync
  version: !binary |-
    YWI0NWYyNTE5OGZhOWQ3MDlmMTcyNDkwOTNmZTc4MmE0YzBhYmM3Nw==
  sha1: !binary |-
    YmVkMTQyNTI2YWQyMzFmMDc1MWYzNjQ3OTczYTQ5ODg0ZmJmNDg2Mw==
  fingerprint: !binary |-
    YWI0NWYyNTE5OGZhOWQ3MDlmMTcyNDkwOTNmZTc4MmE0YzBhYmM3Nw==
  dependencies:
  - golang_1.4
- name: auctioneer
  version: !binary |-
    ZjM0ZDg1NTc0ZTY4NjVkZmUzZmI2MzEzODMyYTNjOGRhZWQwNmQwZg==
  sha1: !binary |-
    YjVhYzA3Y2IzZDJkNDM4NzdmOWNlYTc5YWU1ODRiYjkyMTliYjMyZg==
  fingerprint: !binary |-
    ZjM0ZDg1NTc0ZTY4NjVkZmUzZmI2MzEzODMyYTNjOGRhZWQwNmQwZg==
  dependencies:
  - golang_1.4
- name: smoke-tests
  version: !binary |-
    YjM0MGM1NDFmMWI1Y2ZiZGEzODVjNzkzNzhkMTYxNTE4ZDI5MjUxMw==
  sha1: !binary |-
    YWFkOTg4OTliMzNjM2RlNWY2Y2ZkNTNiMThmZGIwODMxMDcwNTlhYQ==
  fingerprint: !binary |-
    YjM0MGM1NDFmMWI1Y2ZiZGEzODVjNzkzNzhkMTYxNTE4ZDI5MjUxMw==
  dependencies:
  - golang_1.4
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    MGFhZmI4ZDU0M2M3YTExNDdhYzdkMGFhNmMzMzg1NDQyNjRiNjM1MQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: docker-circus
  version: !binary |-
    NzJkN2YwNTc2NjZkYmZmMjIxMTFhODRjNjQ1MjkyMmY3N2UzNWJiNw==
  sha1: !binary |-
    MWI3N2QzNWRiMzA2NjE4MGEyYTI2M2ZlOTIwYTJiNzU1ZTY0MWFlNQ==
  fingerprint: !binary |-
    NzJkN2YwNTc2NjZkYmZmMjIxMTFhODRjNjQ1MjkyMmY3N2UzNWJiNw==
  dependencies:
  - golang_1.4
- name: rootfs_lucid64
  version: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  sha1: !binary |-
    NGUyOTNiNWQwMjBkNmRiZGVhN2FmMjZhYmUzZTRmMDg2NGJjNjFmMg==
  fingerprint: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  dependencies: []
jobs:
- name: route_emitter
  version: !binary |-
    MTczMzM2Mzg1ZmU3MTU0OTE4MGM1N2YyYzUwMTliNDRlZTQyOGE0MA==
  fingerprint: !binary |-
    MTczMzM2Mzg1ZmU3MTU0OTE4MGM1N2YyYzUwMTliNDRlZTQyOGE0MA==
  sha1: !binary |-
    Njg3NDUwNjM2NjI3YjgwZGQ4ZjI0Mzg0NWI5ZDEwMzMzYTNlMzQyZA==
- name: consul-agent
  version: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  fingerprint: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  sha1: !binary |-
    MDExZWM5ZDgyZjcwMzhlYjY3OTdkNDFiMDUyOGQxNGViNTQ4YmIzZg==
- name: etcd_metrics_server
  version: !binary |-
    Zjc5ZTk4NDRmZjA2MzM5MmEyZWU3NTBjMTc2ZGE4ZTgyMTI5YmFiYQ==
  fingerprint: !binary |-
    Zjc5ZTk4NDRmZjA2MzM5MmEyZWU3NTBjMTc2ZGE4ZTgyMTI5YmFiYQ==
  sha1: !binary |-
    ZGFkMWZmZTQ4MWY4MjJmYjc4ZmQzYWM3YTRjZjVhNDAyZjE0OTIwOQ==
- name: runtime_metrics_server
  version: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  fingerprint: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  sha1: !binary |-
    MjFlZDQyOGUwNTEwZDE0YzIwNjg1OGI3YzFjZTFhNTczMDNjOTMyZA==
- name: executor
  version: !binary |-
    NzRlMDQzYmRlZjAzZTBiZmI1MzIyZGQyYzI2NjJjYTFkM2NhNjY0MQ==
  fingerprint: !binary |-
    NzRlMDQzYmRlZjAzZTBiZmI1MzIyZGQyYzI2NjJjYTFkM2NhNjY0MQ==
  sha1: !binary |-
    MzUwNjlkMjJkMDY5NDIwYmI3MDBjMjY2NTAwZmQ2YWE4YTBmZDUyMA==
- name: converger
  version: !binary |-
    MDk3ZGU5NThkOTA2MDIwYjZlOTYxMDI5NWNmNzc0YTFiYmFmYjA1MQ==
  fingerprint: !binary |-
    MDk3ZGU5NThkOTA2MDIwYjZlOTYxMDI5NWNmNzc0YTFiYmFmYjA1MQ==
  sha1: !binary |-
    YzgwNzAwYThkYWU0MTM0MTk4YTUyOTgyODkyZTNlMDMzMGI3OGNjNw==
- name: tps
  version: !binary |-
    ZmIwYmY3Y2U4OThlMDFkMzhiOTZjMThkOWZhYTBjYmYzMWE0N2FkMA==
  fingerprint: !binary |-
    ZmIwYmY3Y2U4OThlMDFkMzhiOTZjMThkOWZhYTBjYmYzMWE0N2FkMA==
  sha1: !binary |-
    MjYzMjZiNGFmNGM4NmJhNGEzYWNhOTJhMmYwNGRjMzY3ODM5N2E5Nw==
- name: etcd
  version: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  fingerprint: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  sha1: !binary |-
    MzFiNDJiOTYwYzBkMWUwMDhkZTE4YmFlNDYxZDI5OTBkZjllNGZjZQ==
- name: acceptance-tests
  version: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  fingerprint: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  sha1: !binary |-
    OGExNDljMDI3NzNhOTJlNDEyOTlkM2IxNjYxNjk3OGU1ZGU5ODA4MQ==
- name: rep
  version: !binary |-
    NzJmNDkwZmY0MGQ3MGU4YjdmMWI1NzA1N2ExNWNiNzM2YjhmODg2MQ==
  fingerprint: !binary |-
    NzJmNDkwZmY0MGQ3MGU4YjdmMWI1NzA1N2ExNWNiNzM2YjhmODg2MQ==
  sha1: !binary |-
    NWE4ZWM2OGI0ZmI1NDhlZTg0Y2FjNzU0NmRiYmVlMzA3ODBhMzFkOA==
- name: receptor
  version: !binary |-
    ZWQyMzQzZTIyOTRhM2JjMGY4NDQxYzRhMWZjMDg3YTE0ZDgzZWQxYQ==
  fingerprint: !binary |-
    ZWQyMzQzZTIyOTRhM2JjMGY4NDQxYzRhMWZjMDg3YTE0ZDgzZWQxYQ==
  sha1: !binary |-
    ZmYzMWNkZjE4NjQyM2UwZmUyNjQzOTQ2MzAxZjM3YmJlZTQ1MDYyYg==
- name: file_server
  version: !binary |-
    MjVmNjg4ZjAzNTJkMDY4MWQ2MWYzYzYzM2Q1ZmViODgwYWVmMGQ1Yg==
  fingerprint: !binary |-
    MjVmNjg4ZjAzNTJkMDY4MWQ2MWYzYzYzM2Q1ZmViODgwYWVmMGQ1Yg==
  sha1: !binary |-
    N2Q3NmMxN2NkMmYxODJkZjZhYzI1NjNmN2ZjMjUzZDE4NWM4OWU3Yw==
- name: garden-linux
  version: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  fingerprint: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  sha1: !binary |-
    NTdlOWJmZTM5ODVhZWI5MzY5Mjc0MGNhZTg4ZTM5YzM1YWI3YTIwMg==
- name: stager
  version: !binary |-
    M2Y5NDRiNGE3YTBjYTdmZDAzMWJkZDkwODg4Mzk0NGI5ZGNiOTRhOQ==
  fingerprint: !binary |-
    M2Y5NDRiNGE3YTBjYTdmZDAzMWJkZDkwODg4Mzk0NGI5ZGNiOTRhOQ==
  sha1: !binary |-
    NmQ5NWQwM2MwYjE0MzEzNTQxZjQ3MmMzZjcwMTE1YzMwMzgyYWNiMA==
- name: nsync
  version: !binary |-
    MzRkNWI4MzZkNDIyYjljZmZiNjY4OTlkYTAxOTUzMDhmOWM4ZTNlMw==
  fingerprint: !binary |-
    MzRkNWI4MzZkNDIyYjljZmZiNjY4OTlkYTAxOTUzMDhmOWM4ZTNlMw==
  sha1: !binary |-
    OWY5ZWE5OTcwYzM4ZmZkYjBiMmU3MTdjMDc1OGViNGY5MjgwMTQwNQ==
- name: auctioneer
  version: !binary |-
    NWU5NzY3ODNjMmE4ZTRhM2QzNjUxNjkyZGE0ZWI0NTVmNTllMDI2Yw==
  fingerprint: !binary |-
    NWU5NzY3ODNjMmE4ZTRhM2QzNjUxNjkyZGE0ZWI0NTVmNTllMDI2Yw==
  sha1: !binary |-
    NmJjNTdmZWZjZDI5NjliY2M0NmRmNDIzYWJhNWM4OTliOWFmNGIwYg==
- name: smoke-tests
  version: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  fingerprint: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  sha1: !binary |-
    YjQxNDIyZTJmN2I0NjIyMzA5NTdkOWZlZGI5MDk0MDBlNmEzOTllNg==
commit_hash: ea841856
uncommitted_changes: false
name: diego
version: '0.696'
