---
packages:
- name: docker-circus
  version: !binary |-
    ZWQ4NjlkNzlkZWFmYzM2Mzg0NjJkM2E0MjQzMzliY2YzMjUzZjNjMA==
  sha1: !binary |-
    OGNmOWE2OGFkZWE4OTNjYzJjMGUwMGY4N2Y1OTAzYTE1NzVlMGIyMg==
  fingerprint: !binary |-
    ZWQ4NjlkNzlkZWFmYzM2Mzg0NjJkM2E0MjQzMzliY2YzMjUzZjNjMA==
  dependencies:
  - golang
- name: garden-linux
  version: !binary |-
    NTcyZjYzZTExMzFjMDRjNjJlMDc3YTZmN2RiYjlhYjNiMzRjMzExOQ==
  sha1: !binary |-
    NGVjMDhkNGRkNTIyZDA0NzY0NjQ2OGVmNmY1YTM0NDA1ZjljOWEyNw==
  fingerprint: !binary |-
    NTcyZjYzZTExMzFjMDRjNjJlMDc3YTZmN2RiYjlhYjNiMzRjMzExOQ==
  dependencies:
  - golang
- name: converger
  version: !binary |-
    Zjc4NWEwYTExODg3ZjViZjVhNTAzNDQzNDNhOTRmYzRmNjRlODA2NA==
  sha1: !binary |-
    NmM1ZTY1OTQ3OTU5ZWJhOWJlZTk0MTc1MjQ1YWM3MjEzNWI2NjRjYg==
  fingerprint: !binary |-
    Zjc4NWEwYTExODg3ZjViZjVhNTAzNDQzNDNhOTRmYzRmNjRlODA2NA==
  dependencies:
  - golang
- name: rep
  version: !binary |-
    YjA2MzgxZjViZTQyZGQ1ZTcyYjAwMTc0OTA2MDdlOTdmZTljMDQyZg==
  sha1: !binary |-
    YmU2Zjg4NWY3NWJhYzUwNDQwMjk5ZjNjZWI4Mzk0Mjc0YTYwMzAzYQ==
  fingerprint: !binary |-
    YjA2MzgxZjViZTQyZGQ1ZTcyYjAwMTc0OTA2MDdlOTdmZTljMDQyZg==
  dependencies:
  - golang
- name: cf-cli
  version: !binary |-
    OTRhNzlmYmFlODdmN2E4ZWMzMDA0MTYyYjFjNTlkMTNhZDY5NzU4OA==
  sha1: !binary |-
    YTM2Mzc1NTkzMTE4YTkxODQ0NTY0ZDY1YjA0YzhkYjk1NzUzYjIwYQ==
  fingerprint: !binary |-
    OTRhNzlmYmFlODdmN2E4ZWMzMDA0MTYyYjFjNTlkMTNhZDY5NzU4OA==
  dependencies: []
- name: file_server
  version: !binary |-
    NDU2N2I3MDY5MWY3ZDY5NTQzNmU3Y2JkODg3ODIzZDk0NGUwZDU4Mg==
  sha1: !binary |-
    YTQ4MTY0MmM4YmZkYzc3Yjk5MTZjODFmNGNmYWNiMzk5ZmIzNThhNQ==
  fingerprint: !binary |-
    NDU2N2I3MDY5MWY3ZDY5NTQzNmU3Y2JkODg3ODIzZDk0NGUwZDU4Mg==
  dependencies:
  - golang
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MTUxMjA2NjY3ZmI0MjQzMTUzYjUwODA2ZTk3YjFmYjdkZTlhOTRjZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: etcd_metrics_server
  version: !binary |-
    YmU5ODcyNTIxZjhhMDM2ZTY0MzkzZGQ2M2M5Y2FkOWU2M2EyOWZkMA==
  sha1: !binary |-
    MjNmMjQ0NWZkZjY0OTI1YWRmNzNkYTI3NjdlZmRjNTJmZGNlNDRhMQ==
  fingerprint: !binary |-
    YmU5ODcyNTIxZjhhMDM2ZTY0MzkzZGQ2M2M5Y2FkOWU2M2EyOWZkMA==
  dependencies:
  - golang
- name: linux-circus
  version: !binary |-
    NmRjNmJjZjZkM2MxMTFjNmQzZDdkZTdiZjhjYzE1OGU5ZGM3YTQxMQ==
  sha1: !binary |-
    NDk0NmI4N2IyY2NlMjZkMGU3MmUzN2U5NjhkZmQwMjI0ZDlkMTg4Mw==
  fingerprint: !binary |-
    NmRjNmJjZjZkM2MxMTFjNmQzZDdkZTdiZjhjYzE1OGU5ZGM3YTQxMQ==
  dependencies:
  - golang
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    ODNlZmQ2ZGE2OGYzMTFhZGFiYzg0OTMxOGU1NjcxMjczODU3YTdjZg==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: nsync
  version: !binary |-
    NDkxOTUzNDc5Njg5Njg0Mjk5YWU4NzgzODljMDJiYTRlZmQ5YTk5OQ==
  sha1: !binary |-
    NGNkNmI3MDUzOGE2NWJmMjc3NjVlNDdhODExOGY3NGU4NDE5NGJhMA==
  fingerprint: !binary |-
    NDkxOTUzNDc5Njg5Njg0Mjk5YWU4NzgzODljMDJiYTRlZmQ5YTk5OQ==
  dependencies:
  - golang
- name: route_emitter
  version: !binary |-
    ZGU2NzY0ZTlkZGUzMWE0NTBmYzQ1MDIzMmZkMDlhNWQwN2NkYTc3Mg==
  sha1: !binary |-
    ODRhMDI2NTBiMmQwZTE2ZDU4NWIxMmNhNjNhNzQyZTQ0M2VjMDQzNw==
  fingerprint: !binary |-
    ZGU2NzY0ZTlkZGUzMWE0NTBmYzQ1MDIzMmZkMDlhNWQwN2NkYTc3Mg==
  dependencies:
  - golang
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    MGFhZmI4ZDU0M2M3YTExNDdhYzdkMGFhNmMzMzg1NDQyNjRiNjM1MQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: smoke-tests
  version: !binary |-
    ZDQwODdkN2Q4NWNmMDQzZDIxMTk5MGJmZWRhNTZlMTRjNmI0YjZiYw==
  sha1: !binary |-
    OTQ4YzIzYjE0MzM3ZmYzNzNiMDA4Yjg5ZGRhOTFkZTNjMmJhYzliMA==
  fingerprint: !binary |-
    ZDQwODdkN2Q4NWNmMDQzZDIxMTk5MGJmZWRhNTZlMTRjNmI0YjZiYw==
  dependencies:
  - golang
- name: acceptance-tests
  version: !binary |-
    OGZjYzVlMzFlMjI4YzcyMzE2NzRhODJjZjJmYzBjOGE3ZWU5MTYzMA==
  sha1: !binary |-
    NTRiMjYyNzEzMTM3YTM4MzBlNDZjMzgzMTgxYmY5MjcwNDE3MTg0OQ==
  fingerprint: !binary |-
    OGZjYzVlMzFlMjI4YzcyMzE2NzRhODJjZjJmYzBjOGE3ZWU5MTYzMA==
  dependencies:
  - golang
- name: auctioneer
  version: !binary |-
    ZGJlM2Y4ZDJkODRmM2U2NmNkMWRkN2Q1NzJkNmI4MzJmMjFiMzI3Yg==
  sha1: !binary |-
    MWU0ZDkxNDRmZmNiZjU1NWJjZDJkNzVlZGIzNjQzOTk3YWZiMjljNA==
  fingerprint: !binary |-
    ZGJlM2Y4ZDJkODRmM2U2NmNkMWRkN2Q1NzJkNmI4MzJmMjFiMzI3Yg==
  dependencies:
  - golang
- name: runtime_metrics_server
  version: !binary |-
    MWJiZDUxNmNlMTQ5YmYyZmRkZDkwMmEyZjNiYTQ3MDRmOGIwMDdhZA==
  sha1: !binary |-
    MzA3MGJhYmM1MjY3ZmU2NTIwMWY1MDA5NzBkMTdmNWQwZWIzNzI5OA==
  fingerprint: !binary |-
    MWJiZDUxNmNlMTQ5YmYyZmRkZDkwMmEyZjNiYTQ3MDRmOGIwMDdhZA==
  dependencies:
  - golang
- name: etcd
  version: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  sha1: !binary |-
    NjdlMWM4Yjk1YzhiNWMzMmIxZjg5ZjNjMjc1YmQ5ZjYxNmExZDc2Yw==
  fingerprint: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  dependencies:
  - golang
- name: rootfs_lucid64
  version: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  sha1: !binary |-
    ZTE1M2YwMzkxNTM2NTZmNjYyNzdkNjAxMDAyMTA1NjRjODY1ZmQzNg==
  fingerprint: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  dependencies: []
- name: tps
  version: !binary |-
    MzZmNTllYTE1M2Y3OGM1MjE0MDg4ZGQ3Nzk2YTlmZDU0ZDk1NmYyOA==
  sha1: !binary |-
    MjJjNWFiYjM3ODExYTQwZGU1MGE2YWU5YzM0MGU3NmY4OTBhYmIwMQ==
  fingerprint: !binary |-
    MzZmNTllYTE1M2Y3OGM1MjE0MDg4ZGQ3Nzk2YTlmZDU0ZDk1NmYyOA==
  dependencies:
  - golang
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    NWIwZmZiYTAxMGIyM2RkMjFlZjIxZTdjMDM4NWQ0NjhhNWRhYTNiMw==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
- name: stager
  version: !binary |-
    ZGYwMjAzNzRjYjM5ZjIxZmQwZDE5ZDM5ODlhMmY2YzFlMjI2OWFmMA==
  sha1: !binary |-
    ODY1NmEzMjg0NDI5M2FmZjI2ZDNmNTdkNTI3MmQxMTcwNmU1ZGRkYQ==
  fingerprint: !binary |-
    ZGYwMjAzNzRjYjM5ZjIxZmQwZDE5ZDM5ODlhMmY2YzFlMjI2OWFmMA==
  dependencies:
  - golang
- name: executor
  version: !binary |-
    NTFlZGE3NTBjZGI3ZGMwNWUwNDBlNmQ4OGVjN2RhN2M0OGQ4ZjYzMg==
  sha1: !binary |-
    YWI5ZDNjYzMyZjZhNWM3YzA2YTViNmYwNzk3ZjUxODE5NzQxZjk1OQ==
  fingerprint: !binary |-
    NTFlZGE3NTBjZGI3ZGMwNWUwNDBlNmQ4OGVjN2RhN2M0OGQ4ZjYzMg==
  dependencies:
  - golang
jobs:
- name: converger
  version: !binary |-
    MjUwYmQ0NTY3M2IwNzcwYzEyN2EyN2YzYmExZjFjOTg5OGVjOGM2MA==
  fingerprint: !binary |-
    MjUwYmQ0NTY3M2IwNzcwYzEyN2EyN2YzYmExZjFjOTg5OGVjOGM2MA==
  sha1: !binary |-
    ZTg3MDBlYmNjOTlhZWFmNWNjMjgwZmZkYjlkNTBlYzliNGVjZTg5ZQ==
- name: rep
  version: !binary |-
    MTg5YjExOTJkOGIwYTM5NzExZmEzNmNlNGUyZTQxODRhOGI4NjM2Zg==
  fingerprint: !binary |-
    MTg5YjExOTJkOGIwYTM5NzExZmEzNmNlNGUyZTQxODRhOGI4NjM2Zg==
  sha1: !binary |-
    NzkyNzJjMDkzZmVlY2VmZjNhZTM4ODA5NDQxY2VlNzcwOGEwZGRkMw==
- name: garden
  version: !binary |-
    NGQ2ZGFlMmQ5MDJmOTU2Y2Y3ODY0ZWYxOWM0ZGM0Yjc5MjZhOWM2ZA==
  fingerprint: !binary |-
    NGQ2ZGFlMmQ5MDJmOTU2Y2Y3ODY0ZWYxOWM0ZGM0Yjc5MjZhOWM2ZA==
  sha1: !binary |-
    MDFkYTcyY2EyNDgwZDVkZTI3OGJmODliNTczZDgwNjkzYWNkNzI1Nw==
- name: file_server
  version: !binary |-
    Y2E1NDc0NWU5NDJmOGU4NDM5ODQ1NjNiYWEyOWNiZTViMTNiMTFhNw==
  fingerprint: !binary |-
    Y2E1NDc0NWU5NDJmOGU4NDM5ODQ1NjNiYWEyOWNiZTViMTNiMTFhNw==
  sha1: !binary |-
    MTFiNzdiMTZiMjhkOTQxNDQ0MzM4ZjcwZWExMjRlNjIyODJiZDJmNA==
- name: etcd_metrics_server
  version: !binary |-
    OGU4NzYzY2Y0ZDY0ZjBjYTEwM2UyOGNiOWYwMTliNGIyYzQwODFlOQ==
  fingerprint: !binary |-
    OGU4NzYzY2Y0ZDY0ZjBjYTEwM2UyOGNiOWYwMTliNGIyYzQwODFlOQ==
  sha1: !binary |-
    YjA2NGNkMmYxODhkZjZlODMyZDIzNTNmNzkwM2EwYmUwOWRhMmQwZg==
- name: nsync
  version: !binary |-
    MDZlOTJkOGY3ZGU3MGU4YzlkZWM1NTdhNDVkODAzOWViZjBhN2Y1ZQ==
  fingerprint: !binary |-
    MDZlOTJkOGY3ZGU3MGU4YzlkZWM1NTdhNDVkODAzOWViZjBhN2Y1ZQ==
  sha1: !binary |-
    NDkxODVmMzVmNmE2MDcxZmNhZTk1MDhhN2MzZWY1MmYwZDZiYWI2Mw==
- name: route_emitter
  version: !binary |-
    OGI2ZjJhOTAyYjc2NmNhMzRkZDhmNDM0YjYwZTRiMTAyNGFkZGNlNA==
  fingerprint: !binary |-
    OGI2ZjJhOTAyYjc2NmNhMzRkZDhmNDM0YjYwZTRiMTAyNGFkZGNlNA==
  sha1: !binary |-
    YmM0YWRmZTA3MjQwYTA2ODU0MDMzZWRhYTEyNjc3OGZlZGE5MzM3MA==
- name: smoke-tests
  version: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  fingerprint: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  sha1: !binary |-
    YjQxNDIyZTJmN2I0NjIyMzA5NTdkOWZlZGI5MDk0MDBlNmEzOTllNg==
- name: acceptance-tests
  version: !binary |-
    MTI0YjA1MDYyYmFlYWJkNGUyNzMyODZjZjE2N2Q2ZTI0NmY3MWJiNA==
  fingerprint: !binary |-
    MTI0YjA1MDYyYmFlYWJkNGUyNzMyODZjZjE2N2Q2ZTI0NmY3MWJiNA==
  sha1: !binary |-
    OTgzYjdiZTljNmEyZjBlY2IyYjNlOWFiNDBiMzQ5ZTA1YjRiNDFlNw==
- name: auctioneer
  version: !binary |-
    N2M4MjM2MDg4ZmJhZTQzZTczNzhmMzY4MzYzN2ZlNjFiYTBiYzg1Yw==
  fingerprint: !binary |-
    N2M4MjM2MDg4ZmJhZTQzZTczNzhmMzY4MzYzN2ZlNjFiYTBiYzg1Yw==
  sha1: !binary |-
    MjNmMDhmOWIxZTcxZjU1OWRkODZlZTMxN2U2MWJiNDc1Nzg2YzkxYw==
- name: runtime_metrics_server
  version: !binary |-
    OThhNTAyNDUwZTczMTk1MDE4NTJiYjc2NWU0OThiZGI2NDYxNTVlNQ==
  fingerprint: !binary |-
    OThhNTAyNDUwZTczMTk1MDE4NTJiYjc2NWU0OThiZGI2NDYxNTVlNQ==
  sha1: !binary |-
    Yjk3ZjM0OTA4MWNkZjMwMjcyMThjZTJmYzRjZThlYmU1YjY2YWE3Yg==
- name: etcd
  version: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  fingerprint: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  sha1: !binary |-
    MzFiNDJiOTYwYzBkMWUwMDhkZTE4YmFlNDYxZDI5OTBkZjllNGZjZQ==
- name: tps
  version: !binary |-
    YThlYjVhOWFhOGU5YWI4YTkxNmZlYzI4MzNhMGQwODljMzA5YzQyNQ==
  fingerprint: !binary |-
    YThlYjVhOWFhOGU5YWI4YTkxNmZlYzI4MzNhMGQwODljMzA5YzQyNQ==
  sha1: !binary |-
    ZTRmZDI2NmYwNDBiZDU0YTc1MjNjZDc5NTU0ZDFlOWE0NjY5ZGNhYw==
- name: stager
  version: !binary |-
    YjgwYjc3ZTQ3MmI3ODcxYmM5ZDI4YTM1YmEwMTY3ZTM3MGQxODVhMQ==
  fingerprint: !binary |-
    YjgwYjc3ZTQ3MmI3ODcxYmM5ZDI4YTM1YmEwMTY3ZTM3MGQxODVhMQ==
  sha1: !binary |-
    ZjljMmVlMzdhYzRmZThjMjdlMTg1NzI3NzhmZWUwYmUxYzdkNjZiMg==
- name: executor
  version: !binary |-
    MmNmNGU0NTQwNzBkNzg1Mzk1YTM4Nzg3Y2RjNWE0ZDE4ZDU3MDlmMw==
  fingerprint: !binary |-
    MmNmNGU0NTQwNzBkNzg1Mzk1YTM4Nzg3Y2RjNWE0ZDE4ZDU3MDlmMw==
  sha1: !binary |-
    ZWJkZDJkOWZlZGI3ZTlmNjc2MjFmMTZlOTY0NzY1MDViZTQ0M2E1Mw==
commit_hash: 457fcb4d
uncommitted_changes: true
name: diego
version: '0.468'
