---
packages:
- name: converger
  version: !binary |-
    MTljMzQ4NzNhN2Y2OTZiOGM2YzVmMzEzNTU3NjA5NjBiZTA0OTliMA==
  sha1: !binary |-
    OWEwYjMxZGZjZmU3M2UyNjE2M2Q3ODI1NTM4ZGU5ODIxYWQ1Mzg3OQ==
  fingerprint: !binary |-
    MTljMzQ4NzNhN2Y2OTZiOGM2YzVmMzEzNTU3NjA5NjBiZTA0OTliMA==
  dependencies:
  - golang_1.4
- name: etcd_metrics_server
  version: !binary |-
    NzEyODNiNmY4ZWI0Zjg4MzgwNTIzNjAxYzJiMDQyYmZlMGZkZGJjNw==
  sha1: !binary |-
    N2EwYzc1MGNkMWRiNjRhYWU1YjU0NzEwZDI2YTc4OGQwMzBhMzhkNw==
  fingerprint: !binary |-
    NzEyODNiNmY4ZWI0Zjg4MzgwNTIzNjAxYzJiMDQyYmZlMGZkZGJjNw==
  dependencies:
  - golang_1.4
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MTUxMjA2NjY3ZmI0MjQzMTUzYjUwODA2ZTk3YjFmYjdkZTlhOTRjZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: rep
  version: !binary |-
    Mjc0MjU0ZmNiMmFlMTIyM2UzYTQ0Yzc2M2RiNGUzZGU3NmMxNjM2NA==
  sha1: !binary |-
    YjdiMDE1YWFlNjA0ODFiOTI1ZTU2MDBkOTgyOGM5MDQ4ODEwYTEzYQ==
  fingerprint: !binary |-
    Mjc0MjU0ZmNiMmFlMTIyM2UzYTQ0Yzc2M2RiNGUzZGU3NmMxNjM2NA==
  dependencies:
  - golang_1.4
- name: rootfs_lucid64
  version: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  sha1: !binary |-
    NGUyOTNiNWQwMjBkNmRiZGVhN2FmMjZhYmUzZTRmMDg2NGJjNjFmMg==
  fingerprint: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  dependencies: []
- name: stager
  version: !binary |-
    ZjczYTg2NDc5NWVlNjVmNWFjZmFhN2Q0ZTBlMzFjOWRkMTFkMzcwMA==
  sha1: !binary |-
    NDlhNzVlODFlODFiMmMzMWQ1YWQ4N2E4YmFlNzdlZTU1ZDE4ZDQ0OQ==
  fingerprint: !binary |-
    ZjczYTg2NDc5NWVlNjVmNWFjZmFhN2Q0ZTBlMzFjOWRkMTFkMzcwMA==
  dependencies:
  - golang_1.4
- name: consul_0.4
  version: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  sha1: !binary |-
    YTlmN2IzZmI2MDZmOWQxMjQ5ZTkwODYxZGUyNGQzYjdjMzFkYjM2Mw==
  fingerprint: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  dependencies: []
- name: file_server
  version: !binary |-
    OGEzYTE3NjU0MWJjOTM4ZjVmZDdlMjUyMzIzNWNkZjYzMjJlZjFjMQ==
  sha1: !binary |-
    NTFiZThhYmJmMDcyMzdmMTVjYzQwMzhlMTA0NDcyZjAyODU4ZmRmMQ==
  fingerprint: !binary |-
    OGEzYTE3NjU0MWJjOTM4ZjVmZDdlMjUyMzIzNWNkZjYzMjJlZjFjMQ==
  dependencies:
  - golang_1.4
- name: docker-circus
  version: !binary |-
    NTcxNmMwMjMwNTY5MTgzMmJlOTQ4NjM2MzI4MDQ4ZmUxYjRiM2U2MA==
  sha1: !binary |-
    NTI1YzAzN2NhYzIzMDVlYWYzMmZhYmI5OTQzZWIwNDVmYzIzMWQ0Ng==
  fingerprint: !binary |-
    NTcxNmMwMjMwNTY5MTgzMmJlOTQ4NjM2MzI4MDQ4ZmUxYjRiM2U2MA==
  dependencies:
  - golang_1.4
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    ODNlZmQ2ZGE2OGYzMTFhZGFiYzg0OTMxOGU1NjcxMjczODU3YTdjZg==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: etcd
  version: !binary |-
    YjNiZWZhOTNjZWJmNGI1NWRkYjVjNjA5Njk1YjM0ZGI4ZTYzMDQ5NQ==
  sha1: !binary |-
    ZTMzMWE3Y2QwZjM5NjRjZmJhOTQxZGU2MTMwMzdmYjQyZGY4YzljYg==
  fingerprint: !binary |-
    YjNiZWZhOTNjZWJmNGI1NWRkYjVjNjA5Njk1YjM0ZGI4ZTYzMDQ5NQ==
  dependencies:
  - golang_1.4
- name: executor
  version: !binary |-
    YjUzNTE1MmUzYzA5ZTBiNWYyYzk4OTMyNTMzODhiMDE4NGUyODVjMQ==
  sha1: !binary |-
    Njk3Y2U4ZmY2YWJiOWJlYmE4MDhhOTVmNmNhN2MxNWZlMDkwZmJhOQ==
  fingerprint: !binary |-
    YjUzNTE1MmUzYzA5ZTBiNWYyYzk4OTMyNTMzODhiMDE4NGUyODVjMQ==
  dependencies:
  - golang_1.4
- name: auctioneer
  version: !binary |-
    YTQ1OGE4ZTM0MDVkOWI4NDU2MzhmODJjZDIzNjZlMzM5ZThkNTUxYg==
  sha1: !binary |-
    YTNkZTNiYzMyMmRjNzc2NmViMGIwOTQyNWFlMGUyMWM1YzRiYzU0OQ==
  fingerprint: !binary |-
    YTQ1OGE4ZTM0MDVkOWI4NDU2MzhmODJjZDIzNjZlMzM5ZThkNTUxYg==
  dependencies:
  - golang_1.4
- name: linux-circus
  version: !binary |-
    MjM5ZTg0OGU1YzA2Mzk0NGEzYmMyZjNmYmE5ODQzMzE5MjUxZjZmZQ==
  sha1: !binary |-
    MTM5MDc4ZjcwODBjMGFiMThjMmE4NWYwOWNlZmUwMThjYzk1ZTIxYw==
  fingerprint: !binary |-
    MjM5ZTg0OGU1YzA2Mzk0NGEzYmMyZjNmYmE5ODQzMzE5MjUxZjZmZQ==
  dependencies:
  - golang_1.4
- name: acceptance-tests
  version: !binary |-
    MTM5MjYxNjk5Y2RlZTA0NmQyNmZiYTA1Yjc1NDVkMzFlNzlkZTUzNQ==
  sha1: !binary |-
    ZjAzZWU5NjEyODY1NzNjYTlkZjczMDU0NmEzMGY5NWRiMjZhMmFjNw==
  fingerprint: !binary |-
    MTM5MjYxNjk5Y2RlZTA0NmQyNmZiYTA1Yjc1NDVkMzFlNzlkZTUzNQ==
  dependencies:
  - golang_1.4
- name: cf-cli
  version: !binary |-
    NjQ1YjY5NTA1MmUzOWJlZGVhNWI3MTdkZDk5MzYwZWY1ZjQ5MmJkZA==
  sha1: !binary |-
    MzQ5MDAxMDdiZWI3NDdlZjQxNjQ1ZTBjYTcxZmE5OTgyNGQwNTgxOQ==
  fingerprint: !binary |-
    NjQ1YjY5NTA1MmUzOWJlZGVhNWI3MTdkZDk5MzYwZWY1ZjQ5MmJkZA==
  dependencies: []
- name: smoke-tests
  version: !binary |-
    ZGFmZmRmM2I3NTkwYjk1YWM5OTcxMzc5MGViYmFhOTI2YWQ1NjRiYQ==
  sha1: !binary |-
    M2NmNTk3ODUwZWEzODJhNWI4MDUyZWRkNzJlZWQyODhiMDljNzNkZQ==
  fingerprint: !binary |-
    ZGFmZmRmM2I3NTkwYjk1YWM5OTcxMzc5MGViYmFhOTI2YWQ1NjRiYQ==
  dependencies:
  - golang_1.4
- name: route_emitter
  version: !binary |-
    MWZlOTUyZGFiM2Y2YTMxZjYzYWY5MWQ2ZGMyMzgyNGI3MDlkMmI2Yw==
  sha1: !binary |-
    M2QyNjViMjJhNDgyZDQ4ZjQ2ZWIzNDQxMmMwYzJjOWNiOTNiY2ZhYQ==
  fingerprint: !binary |-
    MWZlOTUyZGFiM2Y2YTMxZjYzYWY5MWQ2ZGMyMzgyNGI3MDlkMmI2Yw==
  dependencies:
  - golang_1.4
- name: golang_1.4
  version: !binary |-
    ODBmZDEwYWFjYTdmYWZhZGE2ZTdmMjI4ZjAzYzUwMjRmYWEwYjUxYQ==
  sha1: !binary |-
    ZjA5NTMzNGE4N2Q2NmRmOTc0YjA5YzcwMjFlYWQ1MTkxM2E4NjMwNQ==
  fingerprint: !binary |-
    ODBmZDEwYWFjYTdmYWZhZGE2ZTdmMjI4ZjAzYzUwMjRmYWEwYjUxYQ==
  dependencies: []
- name: runtime_metrics_server
  version: !binary |-
    NjQyNzM5MWU5OTdiZjJkYjhlNDM0OGE5MGY2NjYwNGEzYTY0NmQyYg==
  sha1: !binary |-
    NjQ3ZjMzZmIxNGE5NmU3MzUxZjRjYjU2ODYwMzVlNDQyZGE5ZWE4MQ==
  fingerprint: !binary |-
    NjQyNzM5MWU5OTdiZjJkYjhlNDM0OGE5MGY2NjYwNGEzYTY0NmQyYg==
  dependencies:
  - golang_1.4
- name: receptor
  version: !binary |-
    NWJmOWRmZmM4NTYwNDNlMDY2NTY2OTVjZDUyY2Q1OTY3MTRhZWNkMg==
  sha1: !binary |-
    MDAxZTk1NzNkNTA0MDZlMGYzMDNjZWRiODVjZWQwZDg0Y2ZkNTk2OA==
  fingerprint: !binary |-
    NWJmOWRmZmM4NTYwNDNlMDY2NTY2OTVjZDUyY2Q1OTY3MTRhZWNkMg==
  dependencies:
  - golang_1.4
- name: garden-linux
  version: !binary |-
    OGNkYWFjMGZlODk3ZDk3OTVjZDRmN2E5ZjMzY2I4OGZjY2M2MjI5ZQ==
  sha1: !binary |-
    NmU1ZWEyYmYwZGU0ZGY1YjIzZTQzNTUxYjNkYmI5ODUxZWNlYWU0OQ==
  fingerprint: !binary |-
    OGNkYWFjMGZlODk3ZDk3OTVjZDRmN2E5ZjMzY2I4OGZjY2M2MjI5ZQ==
  dependencies:
  - golang_1.4
- name: tps
  version: !binary |-
    ZmY1MzM3MGVjZWFjMGMzYjg1ODg0MGVmZTA3ZWY5ZTAxNGZhN2NmMg==
  sha1: !binary |-
    Y2EzYWQ3NWRhZDc0MTQyYzc4MWI4MGYyOTI5MDI5YWFjNGIwYzczMQ==
  fingerprint: !binary |-
    ZmY1MzM3MGVjZWFjMGMzYjg1ODg0MGVmZTA3ZWY5ZTAxNGZhN2NmMg==
  dependencies:
  - golang_1.4
- name: nsync
  version: !binary |-
    ZGMyN2I2NDNhMGU2ZTE3MWVhNGRmNzkyNjNmOWNmNWE1YjgwYWRjMA==
  sha1: !binary |-
    NjAxZTM3YTQ1MTRhZjRhNWRlMjE5OTMyMDJlNGRmODczOGUwNDk0Yw==
  fingerprint: !binary |-
    ZGMyN2I2NDNhMGU2ZTE3MWVhNGRmNzkyNjNmOWNmNWE1YjgwYWRjMA==
  dependencies:
  - golang_1.4
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    MGFhZmI4ZDU0M2M3YTExNDdhYzdkMGFhNmMzMzg1NDQyNjRiNjM1MQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    NWIwZmZiYTAxMGIyM2RkMjFlZjIxZTdjMDM4NWQ0NjhhNWRhYTNiMw==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
jobs:
- name: converger
  version: !binary |-
    YTI2YWNmMzM2ZDAwYTAzZDkxZWY2ZjZlYWVlMDI0MTFkMmU3YjQwMQ==
  fingerprint: !binary |-
    YTI2YWNmMzM2ZDAwYTAzZDkxZWY2ZjZlYWVlMDI0MTFkMmU3YjQwMQ==
  sha1: !binary |-
    YTMyOWQzN2ZhNzhlMDg1NTE0ZjE5ODM1NGNmODM5ZjhmNTBhZDMzMA==
- name: etcd_metrics_server
  version: !binary |-
    Zjc5ZTk4NDRmZjA2MzM5MmEyZWU3NTBjMTc2ZGE4ZTgyMTI5YmFiYQ==
  fingerprint: !binary |-
    Zjc5ZTk4NDRmZjA2MzM5MmEyZWU3NTBjMTc2ZGE4ZTgyMTI5YmFiYQ==
  sha1: !binary |-
    ZGFkMWZmZTQ4MWY4MjJmYjc4ZmQzYWM3YTRjZjVhNDAyZjE0OTIwOQ==
- name: rep
  version: !binary |-
    NzJmNDkwZmY0MGQ3MGU4YjdmMWI1NzA1N2ExNWNiNzM2YjhmODg2MQ==
  fingerprint: !binary |-
    NzJmNDkwZmY0MGQ3MGU4YjdmMWI1NzA1N2ExNWNiNzM2YjhmODg2MQ==
  sha1: !binary |-
    NWE4ZWM2OGI0ZmI1NDhlZTg0Y2FjNzU0NmRiYmVlMzA3ODBhMzFkOA==
- name: stager
  version: !binary |-
    M2Y5NDRiNGE3YTBjYTdmZDAzMWJkZDkwODg4Mzk0NGI5ZGNiOTRhOQ==
  fingerprint: !binary |-
    M2Y5NDRiNGE3YTBjYTdmZDAzMWJkZDkwODg4Mzk0NGI5ZGNiOTRhOQ==
  sha1: !binary |-
    NmQ5NWQwM2MwYjE0MzEzNTQxZjQ3MmMzZjcwMTE1YzMwMzgyYWNiMA==
- name: consul-agent
  version: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  fingerprint: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  sha1: !binary |-
    MDExZWM5ZDgyZjcwMzhlYjY3OTdkNDFiMDUyOGQxNGViNTQ4YmIzZg==
- name: file_server
  version: !binary |-
    MjVmNjg4ZjAzNTJkMDY4MWQ2MWYzYzYzM2Q1ZmViODgwYWVmMGQ1Yg==
  fingerprint: !binary |-
    MjVmNjg4ZjAzNTJkMDY4MWQ2MWYzYzYzM2Q1ZmViODgwYWVmMGQ1Yg==
  sha1: !binary |-
    N2Q3NmMxN2NkMmYxODJkZjZhYzI1NjNmN2ZjMjUzZDE4NWM4OWU3Yw==
- name: etcd
  version: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  fingerprint: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  sha1: !binary |-
    MzFiNDJiOTYwYzBkMWUwMDhkZTE4YmFlNDYxZDI5OTBkZjllNGZjZQ==
- name: executor
  version: !binary |-
    NzRlMDQzYmRlZjAzZTBiZmI1MzIyZGQyYzI2NjJjYTFkM2NhNjY0MQ==
  fingerprint: !binary |-
    NzRlMDQzYmRlZjAzZTBiZmI1MzIyZGQyYzI2NjJjYTFkM2NhNjY0MQ==
  sha1: !binary |-
    MzUwNjlkMjJkMDY5NDIwYmI3MDBjMjY2NTAwZmQ2YWE4YTBmZDUyMA==
- name: auctioneer
  version: !binary |-
    YzNiYWY4Y2UyNmI4YjE1MTU2YzYzMjU1ZDgyNzE1MDM2YjA1YmNlZQ==
  fingerprint: !binary |-
    YzNiYWY4Y2UyNmI4YjE1MTU2YzYzMjU1ZDgyNzE1MDM2YjA1YmNlZQ==
  sha1: !binary |-
    MGRhMTI5OWJjOWVjNjdlY2Y1ZTc3NmUwNTMzZGJmZDI2OTA0NTc2ZA==
- name: acceptance-tests
  version: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  fingerprint: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  sha1: !binary |-
    OGExNDljMDI3NzNhOTJlNDEyOTlkM2IxNjYxNjk3OGU1ZGU5ODA4MQ==
- name: smoke-tests
  version: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  fingerprint: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  sha1: !binary |-
    YjQxNDIyZTJmN2I0NjIyMzA5NTdkOWZlZGI5MDk0MDBlNmEzOTllNg==
- name: route_emitter
  version: !binary |-
    MTczMzM2Mzg1ZmU3MTU0OTE4MGM1N2YyYzUwMTliNDRlZTQyOGE0MA==
  fingerprint: !binary |-
    MTczMzM2Mzg1ZmU3MTU0OTE4MGM1N2YyYzUwMTliNDRlZTQyOGE0MA==
  sha1: !binary |-
    Njg3NDUwNjM2NjI3YjgwZGQ4ZjI0Mzg0NWI5ZDEwMzMzYTNlMzQyZA==
- name: runtime_metrics_server
  version: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  fingerprint: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  sha1: !binary |-
    MjFlZDQyOGUwNTEwZDE0YzIwNjg1OGI3YzFjZTFhNTczMDNjOTMyZA==
- name: receptor
  version: !binary |-
    ZWQyMzQzZTIyOTRhM2JjMGY4NDQxYzRhMWZjMDg3YTE0ZDgzZWQxYQ==
  fingerprint: !binary |-
    ZWQyMzQzZTIyOTRhM2JjMGY4NDQxYzRhMWZjMDg3YTE0ZDgzZWQxYQ==
  sha1: !binary |-
    ZmYzMWNkZjE4NjQyM2UwZmUyNjQzOTQ2MzAxZjM3YmJlZTQ1MDYyYg==
- name: garden-linux
  version: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  fingerprint: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  sha1: !binary |-
    NTdlOWJmZTM5ODVhZWI5MzY5Mjc0MGNhZTg4ZTM5YzM1YWI3YTIwMg==
- name: tps
  version: !binary |-
    ZmIwYmY3Y2U4OThlMDFkMzhiOTZjMThkOWZhYTBjYmYzMWE0N2FkMA==
  fingerprint: !binary |-
    ZmIwYmY3Y2U4OThlMDFkMzhiOTZjMThkOWZhYTBjYmYzMWE0N2FkMA==
  sha1: !binary |-
    MjYzMjZiNGFmNGM4NmJhNGEzYWNhOTJhMmYwNGRjMzY3ODM5N2E5Nw==
- name: nsync
  version: !binary |-
    MzRkNWI4MzZkNDIyYjljZmZiNjY4OTlkYTAxOTUzMDhmOWM4ZTNlMw==
  fingerprint: !binary |-
    MzRkNWI4MzZkNDIyYjljZmZiNjY4OTlkYTAxOTUzMDhmOWM4ZTNlMw==
  sha1: !binary |-
    OWY5ZWE5OTcwYzM4ZmZkYjBiMmU3MTdjMDc1OGViNGY5MjgwMTQwNQ==
commit_hash: b984acf6
uncommitted_changes: true
name: diego
version: '0.683'
