---
packages:
- name: etcd_metrics_server
  version: !binary |-
    NjMzYTQxMWMwY2Y5MWNiY2UwZjg1MWQ4OGYzZTRkMmMwNzgyOTgyYQ==
  sha1: !binary |-
    MTk2ZWQ3M2JkMmVjZTMwMWFiNDIyYTUwZTE0OGRmNzM0ODAzMDMyMA==
  fingerprint: !binary |-
    NjMzYTQxMWMwY2Y5MWNiY2UwZjg1MWQ4OGYzZTRkMmMwNzgyOTgyYQ==
  dependencies:
  - golang
- name: garden-linux
  version: !binary |-
    ODRlOTlhMDU0YzkzNjk0ZDUzYjE0YWE0NjE5YTA1MzA1NTEzODIwMw==
  sha1: !binary |-
    MWEwZTBmOTU4NmEyYTNhYjM5NWMzYzIyOGE0Mjk5NTZjOGI1YzEyYw==
  fingerprint: !binary |-
    ODRlOTlhMDU0YzkzNjk0ZDUzYjE0YWE0NjE5YTA1MzA1NTEzODIwMw==
  dependencies:
  - golang
- name: file_server
  version: !binary |-
    YTU1YWE3MmY4ZTFhOGI5M2I3MTZiZjQ4OTQ1MDJiMTU4OTUyNmI4Mw==
  sha1: !binary |-
    NGRkZDg0ODQ5NTZjMzQzNDc1NDg2NjdlNTQxOGY1YWY3YjEzYzY3Nw==
  fingerprint: !binary |-
    YTU1YWE3MmY4ZTFhOGI5M2I3MTZiZjQ4OTQ1MDJiMTU4OTUyNmI4Mw==
  dependencies:
  - golang
- name: stager
  version: !binary |-
    YzA4NjI3MmY3YzYyZDY1YmM2NTJlMDk0ZDljZjdhY2EwNzgyOTYwYw==
  sha1: !binary |-
    OGNlOTg0MTIzNWZkYzgyNzViYWE4NDIzMmQ0YWQ1MmFlZmUzMjZlOA==
  fingerprint: !binary |-
    YzA4NjI3MmY3YzYyZDY1YmM2NTJlMDk0ZDljZjdhY2EwNzgyOTYwYw==
  dependencies:
  - golang
- name: syslog_forwarder
  version: !binary |-
    OTVkZDcxNTI4NDU5YWU2MjFkZDhlODFhYzU5ZTViNWM4ZGE3NDdiNA==
  sha1: !binary |-
    ZTljYmE1OTRkNmRhNzJlMTJkNzZiZmYzOWI4ZjI1NWNjOGMwMTU2Ng==
  fingerprint: !binary |-
    OTVkZDcxNTI4NDU5YWU2MjFkZDhlODFhYzU5ZTViNWM4ZGE3NDdiNA==
  dependencies: []
- name: rep
  version: !binary |-
    ZDkyYzk2MWEzODE5ZGE1NGVhYzNmNTVmNDgwNGRiZTM0YzBjZDc1Yw==
  sha1: !binary |-
    ODk5MjZhZmY4ZmJlZmYxZjNjODlkNDk3ZjdhZGUxYzA2NjRhNjBkNA==
  fingerprint: !binary |-
    ZDkyYzk2MWEzODE5ZGE1NGVhYzNmNTVmNDgwNGRiZTM0YzBjZDc1Yw==
  dependencies:
  - golang
- name: converger
  version: !binary |-
    MzI3NmUxMTNlYmU5NzliODVhY2NlZWFhZDYyYzJjNjkzYWVmMTJhZQ==
  sha1: !binary |-
    MjhmZTdhY2Y1MjIxZDBlNTFhYTE4ODJmOTRmNzA3MGE4OWEzOWU2NQ==
  fingerprint: !binary |-
    MzI3NmUxMTNlYmU5NzliODVhY2NlZWFhZDYyYzJjNjkzYWVmMTJhZQ==
  dependencies:
  - golang
- name: tps
  version: !binary |-
    Mzg2MjYyNDM4ZGYxNTAxYjAxZmM2N2QyYjE0ZDg0M2ZlYWM0NzY3ZQ==
  sha1: !binary |-
    YjUzZDRiZjI0YzMxM2E0MDVmMTE5MzhjYTczNGU5YTQwNTg2YmI3MA==
  fingerprint: !binary |-
    Mzg2MjYyNDM4ZGYxNTAxYjAxZmM2N2QyYjE0ZDg0M2ZlYWM0NzY3ZQ==
  dependencies:
  - golang
- name: auctioneer
  version: !binary |-
    M2Y2NjQ4ZDIzNTIzZTJhOTQ0ZjZhNjgxNzg5ZmRiY2NmMGY3MmY2Yw==
  sha1: !binary |-
    ZmFhMGNhNzU5YjEyYzc1NmIzZjU3MDg2MmJmZDM5MWE5NWE3NDc5OA==
  fingerprint: !binary |-
    M2Y2NjQ4ZDIzNTIzZTJhOTQ0ZjZhNjgxNzg5ZmRiY2NmMGY3MmY2Yw==
  dependencies:
  - golang
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MTUxMjA2NjY3ZmI0MjQzMTUzYjUwODA2ZTk3YjFmYjdkZTlhOTRjZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    ODNlZmQ2ZGE2OGYzMTFhZGFiYzg0OTMxOGU1NjcxMjczODU3YTdjZg==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: nsync
  version: !binary |-
    ZGYzNGM0YTVmNGJjMjU2NWFmOTljY2E2MDA5M2NkNzA3ZTEzYzExNQ==
  sha1: !binary |-
    NTliNDJhYzk2YjViNDg2ZTg3ZDI4OWM3YmEwMjQ5ZmNjYTU2YjAwYg==
  fingerprint: !binary |-
    ZGYzNGM0YTVmNGJjMjU2NWFmOTljY2E2MDA5M2NkNzA3ZTEzYzExNQ==
  dependencies:
  - golang
- name: rootfs_lucid64
  version: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  sha1: !binary |-
    ZTE1M2YwMzkxNTM2NTZmNjYyNzdkNjAxMDAyMTA1NjRjODY1ZmQzNg==
  fingerprint: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  dependencies: []
- name: linux-circus
  version: !binary |-
    N2FhNTBiMGFlYzYzNDZkYjIxZjNiYWJkZDYwZGFkZmZmMWQ3ZTBhMw==
  sha1: !binary |-
    YjBiOWFhMmI5YWU4MDYwZjdkOTI1Zjg3MjM0Yjc0N2ViYTQ0NjNlMw==
  fingerprint: !binary |-
    N2FhNTBiMGFlYzYzNDZkYjIxZjNiYWJkZDYwZGFkZmZmMWQ3ZTBhMw==
  dependencies:
  - golang
- name: executor
  version: !binary |-
    OGRlNjY4OTEyY2UyYWQyZjhjMzNlYjllZjQ2Zjk0ZDE3ZDgxOTFmNg==
  sha1: !binary |-
    NTk3YzczMmU0NDQ3ZTc1NDgzNDhjMGM4MTk5ZDI3NzljZGM1NTYyOA==
  fingerprint: !binary |-
    OGRlNjY4OTEyY2UyYWQyZjhjMzNlYjllZjQ2Zjk0ZDE3ZDgxOTFmNg==
  dependencies:
  - golang
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    NWIwZmZiYTAxMGIyM2RkMjFlZjIxZTdjMDM4NWQ0NjhhNWRhYTNiMw==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
- name: etcd
  version: !binary |-
    MGIwMGFlMWZlZDRkMjljNjliNmI1ZDhhMmRkMGQ4NDFhM2I0OTBlNg==
  sha1: !binary |-
    ZmVlMGMyNTE1NDI1ZWM2MTIzNzJmYTc3N2I5YTk2M2UxNWJmY2EzMg==
  fingerprint: !binary |-
    MGIwMGFlMWZlZDRkMjljNjliNmI1ZDhhMmRkMGQ4NDFhM2I0OTBlNg==
  dependencies:
  - golang
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    MGFhZmI4ZDU0M2M3YTExNDdhYzdkMGFhNmMzMzg1NDQyNjRiNjM1MQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: runtime_metrics_server
  version: !binary |-
    ZWY5ZTgxZGQyNzE1YzVlMTk3N2M0MGRhZjIwYzZkMTQzMTMxMDgxMQ==
  sha1: !binary |-
    MWU1YjA5MDhmYTg2MWQ0YTI5NzU5YzNhMDRlYTdiMmEyM2M0YmFhNQ==
  fingerprint: !binary |-
    ZWY5ZTgxZGQyNzE1YzVlMTk3N2M0MGRhZjIwYzZkMTQzMTMxMDgxMQ==
  dependencies:
  - golang
- name: route_emitter
  version: !binary |-
    ZWQxNTI0YWQxYTU3NGNmMDVjOGM3MWQ3MzFjMDM1ZmVkYzhmYTY1MA==
  sha1: !binary |-
    N2VhNWIyNTRkNzMyNTRjYzg4M2FjZmYxZDk1ZWM5YzJiMjUwOTZkOQ==
  fingerprint: !binary |-
    ZWQxNTI0YWQxYTU3NGNmMDVjOGM3MWQ3MzFjMDM1ZmVkYzhmYTY1MA==
  dependencies:
  - golang
- name: docker-circus
  version: !binary |-
    ZGEzNzIzNTY3NWJhNjZhNjJkNWU2ZGFjNTBmMzAxYjc2YjkwOGE0ZQ==
  sha1: !binary |-
    ZThiMWJhYzBjOTMxMzk0ZDdkYjU4NzU0YzY4YzZiNWY1NzBjMTVjMg==
  fingerprint: !binary |-
    ZGEzNzIzNTY3NWJhNjZhNjJkNWU2ZGFjNTBmMzAxYjc2YjkwOGE0ZQ==
  dependencies:
  - golang
jobs:
- name: etcd_metrics_server
  version: !binary |-
    NDE0ZGRjYzFkM2MzYzQxODMzYjVkOTdhN2QzYmZiZGUzM2QzZDVjNQ==
  fingerprint: !binary |-
    NDE0ZGRjYzFkM2MzYzQxODMzYjVkOTdhN2QzYmZiZGUzM2QzZDVjNQ==
  sha1: !binary |-
    OTdkOGY3NGYzZmEyZDMwMzQ1Njg1OGU5ZjlmMWM3NTQ0OTdjMTZlYQ==
- name: file_server
  version: !binary |-
    ZWViYTUyZjRjZjkzZGU5Yzg1ZmJlMjQyY2I0ZTJkMTE3YmNjNWMzZQ==
  fingerprint: !binary |-
    ZWViYTUyZjRjZjkzZGU5Yzg1ZmJlMjQyY2I0ZTJkMTE3YmNjNWMzZQ==
  sha1: !binary |-
    OThlYmIzZjg4NzFlNDMzMDRjMmQ1YzhmZjUzNTkxMjgwODZmNmM0YQ==
- name: stager
  version: !binary |-
    NmM5OTZjYmZiNjRkYWNhZjQ3ZDM5MTc1ODYzNTNiYmQ5ZTJhNWQ3OQ==
  fingerprint: !binary |-
    NmM5OTZjYmZiNjRkYWNhZjQ3ZDM5MTc1ODYzNTNiYmQ5ZTJhNWQ3OQ==
  sha1: !binary |-
    OTgwYzRiZDdiMGM5ZWIwY2JhMzZmN2RmNTdjNmVjNTZlZjYxMDViMQ==
- name: rep
  version: !binary |-
    MGU3ZjczYmYxNWZkZGYyYTBlYmMwNDZjMjdiOTdkMDgwNDhiN2Q0ZA==
  fingerprint: !binary |-
    MGU3ZjczYmYxNWZkZGYyYTBlYmMwNDZjMjdiOTdkMDgwNDhiN2Q0ZA==
  sha1: !binary |-
    OGMxNGFjMTgyYWE1OTRhNzk1MzEwNTYwMzJjMmQyMzEzZTAxMDYzOA==
- name: converger
  version: !binary |-
    MjQyN2YzNGQ1OWRjOGI5N2ZiMWY4NTgzNWFhZGQ1YmY1YjYxMDA3Nw==
  fingerprint: !binary |-
    MjQyN2YzNGQ1OWRjOGI5N2ZiMWY4NTgzNWFhZGQ1YmY1YjYxMDA3Nw==
  sha1: !binary |-
    NjJmZDBkMjJmMzhmOWVmMWNjNTA2ODA3NzA5Y2Q2NGNjNDliNDNmNA==
- name: tps
  version: !binary |-
    Y2E3ODEyYjc0YmQwZmU4MjE3NTIzMzliNTA0NGQzN2UxN2VmYjllMg==
  fingerprint: !binary |-
    Y2E3ODEyYjc0YmQwZmU4MjE3NTIzMzliNTA0NGQzN2UxN2VmYjllMg==
  sha1: !binary |-
    ZDEzMDNhYzU2ZjVjZGI4ZjI5ZjYyZDhjZDlhZjI4YTZhMWUwNWZiZA==
- name: auctioneer
  version: !binary |-
    YTdmMTdmZDUzMTkwYzE1NTFjMzBlZTYzNDIzOWNkYWVhZWEyNmE4NA==
  fingerprint: !binary |-
    YTdmMTdmZDUzMTkwYzE1NTFjMzBlZTYzNDIzOWNkYWVhZWEyNmE4NA==
  sha1: !binary |-
    NGY0ZmI0MjM3NDY2OTA0ZWU3MDY1MzE0NTk4MzNlOWQ4MTc5OTU2NA==
- name: nsync
  version: !binary |-
    ZGMzMWE5YWQyODFjYWE2ZDU1NGUwNGI1N2QwMmYwZjNlNDczMDY5Mw==
  fingerprint: !binary |-
    ZGMzMWE5YWQyODFjYWE2ZDU1NGUwNGI1N2QwMmYwZjNlNDczMDY5Mw==
  sha1: !binary |-
    NTJlNWQ5MDYwZmNlMDA4Y2JmODJkZjE1MTc1NmM4OTM0NWIwNDMzMQ==
- name: executor
  version: !binary |-
    NmE2MzI3NzE4NmIxOWExOTE1NmU1Y2VjZGEwMjZiOTA3YWJiMmNmNw==
  fingerprint: !binary |-
    NmE2MzI3NzE4NmIxOWExOTE1NmU1Y2VjZGEwMjZiOTA3YWJiMmNmNw==
  sha1: !binary |-
    YThmMmYyNWE5MjBjM2Q0YzBmZGE0YzZjZTIwNjZjNTZhZDcxMTU4NQ==
- name: warden
  version: !binary |-
    MGVkMzhmNDJkZDc2MzIyYjliNWQxYmM4MzdmZTE0Nzg0MWEwNjU5Mw==
  fingerprint: !binary |-
    MGVkMzhmNDJkZDc2MzIyYjliNWQxYmM4MzdmZTE0Nzg0MWEwNjU5Mw==
  sha1: !binary |-
    M2RiODIzZWQ0ZDlkMTEzNGFlMDIwYzQwN2UxNmE0OWJmZjllYzE3ZA==
- name: etcd
  version: !binary |-
    OTc4N2NlZGMxYWFiMjYxMDc2NWU4Y2E5MzM4OWIxMDg1ZmE1NTkzMw==
  fingerprint: !binary |-
    OTc4N2NlZGMxYWFiMjYxMDc2NWU4Y2E5MzM4OWIxMDg1ZmE1NTkzMw==
  sha1: !binary |-
    ZDQ3OGQ1YzY0MTFmODBhMWYwMWZhMGRhZGUwMWY5NTk5ZDA2ZmNkMQ==
- name: runtime_metrics_server
  version: !binary |-
    MDIwMmQ3OTlmOTM1YjZhMjUxOTVkNzkwY2IyYjZkNGNjMWY0M2NjOA==
  fingerprint: !binary |-
    MDIwMmQ3OTlmOTM1YjZhMjUxOTVkNzkwY2IyYjZkNGNjMWY0M2NjOA==
  sha1: !binary |-
    MWU5YjMzZmEwNDcyNjI3NmEyZjZlNTQ0ZDRlZTA3YjJmYjI0NmY4Nw==
- name: route_emitter
  version: !binary |-
    ZmNmNzhiN2E2Mzk3YmU1YmQ3NTI0MjViNDU2MzJiZDAxODViMjdiYw==
  fingerprint: !binary |-
    ZmNmNzhiN2E2Mzk3YmU1YmQ3NTI0MjViNDU2MzJiZDAxODViMjdiYw==
  sha1: !binary |-
    MzM4OTI0YTAwMGU5Nzc1YzQ1MmQxOWM4MWZlZTM1MzQxOTA3OTk4ZA==
commit_hash: 9945eb4c
uncommitted_changes: false
name: diego
version: '0.376'
