---
packages:
- name: docker-circus
  version: !binary |-
    MWZiZDJjNjhkYTc4NTY5OTRiOWMzZTY4YmQyNjRmOTIxZDE0OWI1OQ==
  sha1: !binary |-
    NTdmNTYxMTlkNDllOTJiMjNiOGFjNzRmNDExZDIzMTA1NmYwOGVlNw==
  fingerprint: !binary |-
    MWZiZDJjNjhkYTc4NTY5OTRiOWMzZTY4YmQyNjRmOTIxZDE0OWI1OQ==
  dependencies:
  - golang
- name: etcd_metrics_server
  version: !binary |-
    OWVmOTQwMDA2YTljZjc2ZmVjYTY0MTI2OTViOWJjNDI4NmIxMmM5Mg==
  sha1: !binary |-
    YWQ2NGUyMzU2OTMxODkxNjM3MmNmNGYyYzkxYjVhMDI2N2I1MzZkOQ==
  fingerprint: !binary |-
    OWVmOTQwMDA2YTljZjc2ZmVjYTY0MTI2OTViOWJjNDI4NmIxMmM5Mg==
  dependencies:
  - golang
- name: acceptance-tests
  version: !binary |-
    OTAzMTAzZmQwMzFmMTU1ZmM1Mjk3NDE3OWI4ZTlkMWNhMjk2YWI4OQ==
  sha1: !binary |-
    MDE4MjA4MWJkYjYzOWIwYmMyZTNjNzhlZWRhMGE4ODVjMGE5NmU1YQ==
  fingerprint: !binary |-
    OTAzMTAzZmQwMzFmMTU1ZmM1Mjk3NDE3OWI4ZTlkMWNhMjk2YWI4OQ==
  dependencies:
  - golang
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    MGFhZmI4ZDU0M2M3YTExNDdhYzdkMGFhNmMzMzg1NDQyNjRiNjM1MQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: executor
  version: !binary |-
    N2M4ZWEwMjA0NDIwYzAyNjNkOTE2Mjc5MGI1ZmY5NDg1ZTYxZWIzNg==
  sha1: !binary |-
    MmVhN2Y2ZDU1NjU2M2U2MGQzYmY5MjFlMDNhZDNiNGU1MzZkNGNjNw==
  fingerprint: !binary |-
    N2M4ZWEwMjA0NDIwYzAyNjNkOTE2Mjc5MGI1ZmY5NDg1ZTYxZWIzNg==
  dependencies:
  - golang
- name: file_server
  version: !binary |-
    ZmNhYThjMjEyYjE0NTNmMDc3YjBkYzU5NjQ0ODIyNjRjZDhiZjVjOA==
  sha1: !binary |-
    MjQ4NmE1ZWM5NTEzNWNlNjIxZDY1YmEwMmQwY2U2YTc2Mzc1ODc0MA==
  fingerprint: !binary |-
    ZmNhYThjMjEyYjE0NTNmMDc3YjBkYzU5NjQ0ODIyNjRjZDhiZjVjOA==
  dependencies:
  - golang
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    NWIwZmZiYTAxMGIyM2RkMjFlZjIxZTdjMDM4NWQ0NjhhNWRhYTNiMw==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
- name: rootfs_lucid64
  version: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  sha1: !binary |-
    ZTE1M2YwMzkxNTM2NTZmNjYyNzdkNjAxMDAyMTA1NjRjODY1ZmQzNg==
  fingerprint: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  dependencies: []
- name: smoke-tests
  version: !binary |-
    YzZhYjAwN2JjYTdjNzA3ODgwNzVlOWMwMDQ1MWYwNzdiOTBhZDBkZg==
  sha1: !binary |-
    YTA2ODdjYTAxNWEzN2YzM2E5OTBlNmJhZDJjNTM3ZWQwY2FkMjQwMA==
  fingerprint: !binary |-
    YzZhYjAwN2JjYTdjNzA3ODgwNzVlOWMwMDQ1MWYwNzdiOTBhZDBkZg==
  dependencies:
  - golang
- name: runtime_metrics_server
  version: !binary |-
    ZThiODZmODc5ZDBkYWEwYjMxYTExYTI5OWY5NTI1MTI0YTY4NGQ4OA==
  sha1: !binary |-
    ZDE4MTExNWMzY2E0MzAxNzhkYWVmZWIwYWZjYTNhNzExYWI4NDc5ZQ==
  fingerprint: !binary |-
    ZThiODZmODc5ZDBkYWEwYjMxYTExYTI5OWY5NTI1MTI0YTY4NGQ4OA==
  dependencies:
  - golang
- name: garden-linux
  version: !binary |-
    OWI1ZDUzN2UzYWUyZjY0NDY3MGIwZDlhNmEzMWEwNTM4ZDdjNWUwMg==
  sha1: !binary |-
    ZTY4NmI4YTZhMWVmZjI2MDBjZDNmODRhMTljZDY2NDY1MzAxY2Q5YQ==
  fingerprint: !binary |-
    OWI1ZDUzN2UzYWUyZjY0NDY3MGIwZDlhNmEzMWEwNTM4ZDdjNWUwMg==
  dependencies:
  - golang
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    ODNlZmQ2ZGE2OGYzMTFhZGFiYzg0OTMxOGU1NjcxMjczODU3YTdjZg==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: cf-cli
  version: !binary |-
    OTRhNzlmYmFlODdmN2E4ZWMzMDA0MTYyYjFjNTlkMTNhZDY5NzU4OA==
  sha1: !binary |-
    YTM2Mzc1NTkzMTE4YTkxODQ0NTY0ZDY1YjA0YzhkYjk1NzUzYjIwYQ==
  fingerprint: !binary |-
    OTRhNzlmYmFlODdmN2E4ZWMzMDA0MTYyYjFjNTlkMTNhZDY5NzU4OA==
  dependencies: []
- name: stager
  version: !binary |-
    OWIyNTI4ZGNiYmE2NmUzNTdhNGJiYTc5ZDFhNDU2ZDNhMDNjNTgzNA==
  sha1: !binary |-
    NmIyZmQyY2E1ZDVhM2EzM2Y2NmM0ZjBlODEwZmNhMzhiM2RhMjUzZA==
  fingerprint: !binary |-
    OWIyNTI4ZGNiYmE2NmUzNTdhNGJiYTc5ZDFhNDU2ZDNhMDNjNTgzNA==
  dependencies:
  - golang
- name: auctioneer
  version: !binary |-
    NzYxYzY4M2UwOGY0ZGU2MDgwMDY2NjdjMjc4NTQ1ZDgxNmZkODdkOQ==
  sha1: !binary |-
    YTIxMzUzMWZjMDYwYTRhMGI5Mzc3MDkzZmVmYTRkZmEyMTA5ZGVlZg==
  fingerprint: !binary |-
    NzYxYzY4M2UwOGY0ZGU2MDgwMDY2NjdjMjc4NTQ1ZDgxNmZkODdkOQ==
  dependencies:
  - golang
- name: tps
  version: !binary |-
    OTc5NTk4Y2E3YjZhM2FiMzVkYjE3N2FhMzVjZDkxMmI5M2ViZTNlYg==
  sha1: !binary |-
    ZDVkYjcxYTczMjAxZDVlNTM3NDRjNGRkMjRiYWEzNTI4NjdiNmU2OQ==
  fingerprint: !binary |-
    OTc5NTk4Y2E3YjZhM2FiMzVkYjE3N2FhMzVjZDkxMmI5M2ViZTNlYg==
  dependencies:
  - golang
- name: rep
  version: !binary |-
    ZmY0NDEzYjY0MDliZWRjYjhkZmI0YmZlNzkxOTY1NzJhYjgyZWRlMw==
  sha1: !binary |-
    MzhmNmE5NzM1OWI1ZWQ3YTkxMjg4YzUzNmQ3MDViYjc0MDBjZWU3NQ==
  fingerprint: !binary |-
    ZmY0NDEzYjY0MDliZWRjYjhkZmI0YmZlNzkxOTY1NzJhYjgyZWRlMw==
  dependencies:
  - golang
- name: linux-circus
  version: !binary |-
    YTk1ZWY5ZDhhNTkxNmEwN2U0N2EyZTk1NmNmMDJmN2RlOWJmNjlhZQ==
  sha1: !binary |-
    ZWQwNzc3YWEwZmRiNDU3MzRhZDg2ZWJmZjUyYjlhY2UxNDI3MTI2Yw==
  fingerprint: !binary |-
    YTk1ZWY5ZDhhNTkxNmEwN2U0N2EyZTk1NmNmMDJmN2RlOWJmNjlhZQ==
  dependencies:
  - golang
- name: route_emitter
  version: !binary |-
    NDFjMGE3MjEyNmU2NjM2Mzg1ZmY0NGZjYjRkYjI0Yjc5ZDM4NjIxMQ==
  sha1: !binary |-
    MDAwZTRlZGY5ZGJlMDliZGNmZDlhYjExYWZkNDBmYmYxZjQ2MzRmZA==
  fingerprint: !binary |-
    NDFjMGE3MjEyNmU2NjM2Mzg1ZmY0NGZjYjRkYjI0Yjc5ZDM4NjIxMQ==
  dependencies:
  - golang
- name: nsync
  version: !binary |-
    ZTdhY2M1NGE4OTQ3MjY4OTliZmI1ZTVmZTc5ZmUxMTA4M2NlOWFhOQ==
  sha1: !binary |-
    OWVkOTRkY2VlMDY2NGZmY2ZmZDExYjA4YmEyYmQ2Y2I0MmNhYzRlYQ==
  fingerprint: !binary |-
    ZTdhY2M1NGE4OTQ3MjY4OTliZmI1ZTVmZTc5ZmUxMTA4M2NlOWFhOQ==
  dependencies:
  - golang
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MTUxMjA2NjY3ZmI0MjQzMTUzYjUwODA2ZTk3YjFmYjdkZTlhOTRjZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: converger
  version: !binary |-
    ZTliZWQ5ZWQyNjY0YWI3YWFlYmU5ZjlhZjQxYmQwOTNlMmQwMDgzNw==
  sha1: !binary |-
    OGNhNGI0ODEzMWI1ZjcyNjAzOTlhOTUzMTA0YTBjNTJlYjIyYmQzYw==
  fingerprint: !binary |-
    ZTliZWQ5ZWQyNjY0YWI3YWFlYmU5ZjlhZjQxYmQwOTNlMmQwMDgzNw==
  dependencies:
  - golang
- name: etcd
  version: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  sha1: !binary |-
    NjdlMWM4Yjk1YzhiNWMzMmIxZjg5ZjNjMjc1YmQ5ZjYxNmExZDc2Yw==
  fingerprint: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  dependencies:
  - golang
jobs:
- name: etcd_metrics_server
  version: !binary |-
    OGU4NzYzY2Y0ZDY0ZjBjYTEwM2UyOGNiOWYwMTliNGIyYzQwODFlOQ==
  fingerprint: !binary |-
    OGU4NzYzY2Y0ZDY0ZjBjYTEwM2UyOGNiOWYwMTliNGIyYzQwODFlOQ==
  sha1: !binary |-
    YjA2NGNkMmYxODhkZjZlODMyZDIzNTNmNzkwM2EwYmUwOWRhMmQwZg==
- name: acceptance-tests
  version: !binary |-
    MTI0YjA1MDYyYmFlYWJkNGUyNzMyODZjZjE2N2Q2ZTI0NmY3MWJiNA==
  fingerprint: !binary |-
    MTI0YjA1MDYyYmFlYWJkNGUyNzMyODZjZjE2N2Q2ZTI0NmY3MWJiNA==
  sha1: !binary |-
    OTgzYjdiZTljNmEyZjBlY2IyYjNlOWFiNDBiMzQ5ZTA1YjRiNDFlNw==
- name: executor
  version: !binary |-
    MmNmNGU0NTQwNzBkNzg1Mzk1YTM4Nzg3Y2RjNWE0ZDE4ZDU3MDlmMw==
  fingerprint: !binary |-
    MmNmNGU0NTQwNzBkNzg1Mzk1YTM4Nzg3Y2RjNWE0ZDE4ZDU3MDlmMw==
  sha1: !binary |-
    ZWJkZDJkOWZlZGI3ZTlmNjc2MjFmMTZlOTY0NzY1MDViZTQ0M2E1Mw==
- name: file_server
  version: !binary |-
    Y2E1NDc0NWU5NDJmOGU4NDM5ODQ1NjNiYWEyOWNiZTViMTNiMTFhNw==
  fingerprint: !binary |-
    Y2E1NDc0NWU5NDJmOGU4NDM5ODQ1NjNiYWEyOWNiZTViMTNiMTFhNw==
  sha1: !binary |-
    MTFiNzdiMTZiMjhkOTQxNDQ0MzM4ZjcwZWExMjRlNjIyODJiZDJmNA==
- name: smoke-tests
  version: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  fingerprint: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  sha1: !binary |-
    YjQxNDIyZTJmN2I0NjIyMzA5NTdkOWZlZGI5MDk0MDBlNmEzOTllNg==
- name: runtime_metrics_server
  version: !binary |-
    OThhNTAyNDUwZTczMTk1MDE4NTJiYjc2NWU0OThiZGI2NDYxNTVlNQ==
  fingerprint: !binary |-
    OThhNTAyNDUwZTczMTk1MDE4NTJiYjc2NWU0OThiZGI2NDYxNTVlNQ==
  sha1: !binary |-
    Yjk3ZjM0OTA4MWNkZjMwMjcyMThjZTJmYzRjZThlYmU1YjY2YWE3Yg==
- name: stager
  version: !binary |-
    YjgwYjc3ZTQ3MmI3ODcxYmM5ZDI4YTM1YmEwMTY3ZTM3MGQxODVhMQ==
  fingerprint: !binary |-
    YjgwYjc3ZTQ3MmI3ODcxYmM5ZDI4YTM1YmEwMTY3ZTM3MGQxODVhMQ==
  sha1: !binary |-
    ZjljMmVlMzdhYzRmZThjMjdlMTg1NzI3NzhmZWUwYmUxYzdkNjZiMg==
- name: auctioneer
  version: !binary |-
    N2M4MjM2MDg4ZmJhZTQzZTczNzhmMzY4MzYzN2ZlNjFiYTBiYzg1Yw==
  fingerprint: !binary |-
    N2M4MjM2MDg4ZmJhZTQzZTczNzhmMzY4MzYzN2ZlNjFiYTBiYzg1Yw==
  sha1: !binary |-
    MjNmMDhmOWIxZTcxZjU1OWRkODZlZTMxN2U2MWJiNDc1Nzg2YzkxYw==
- name: tps
  version: !binary |-
    YThlYjVhOWFhOGU5YWI4YTkxNmZlYzI4MzNhMGQwODljMzA5YzQyNQ==
  fingerprint: !binary |-
    YThlYjVhOWFhOGU5YWI4YTkxNmZlYzI4MzNhMGQwODljMzA5YzQyNQ==
  sha1: !binary |-
    ZTRmZDI2NmYwNDBiZDU0YTc1MjNjZDc5NTU0ZDFlOWE0NjY5ZGNhYw==
- name: rep
  version: !binary |-
    MTg5YjExOTJkOGIwYTM5NzExZmEzNmNlNGUyZTQxODRhOGI4NjM2Zg==
  fingerprint: !binary |-
    MTg5YjExOTJkOGIwYTM5NzExZmEzNmNlNGUyZTQxODRhOGI4NjM2Zg==
  sha1: !binary |-
    NzkyNzJjMDkzZmVlY2VmZjNhZTM4ODA5NDQxY2VlNzcwOGEwZGRkMw==
- name: route_emitter
  version: !binary |-
    OGI2ZjJhOTAyYjc2NmNhMzRkZDhmNDM0YjYwZTRiMTAyNGFkZGNlNA==
  fingerprint: !binary |-
    OGI2ZjJhOTAyYjc2NmNhMzRkZDhmNDM0YjYwZTRiMTAyNGFkZGNlNA==
  sha1: !binary |-
    YmM0YWRmZTA3MjQwYTA2ODU0MDMzZWRhYTEyNjc3OGZlZGE5MzM3MA==
- name: nsync
  version: !binary |-
    MDZlOTJkOGY3ZGU3MGU4YzlkZWM1NTdhNDVkODAzOWViZjBhN2Y1ZQ==
  fingerprint: !binary |-
    MDZlOTJkOGY3ZGU3MGU4YzlkZWM1NTdhNDVkODAzOWViZjBhN2Y1ZQ==
  sha1: !binary |-
    NDkxODVmMzVmNmE2MDcxZmNhZTk1MDhhN2MzZWY1MmYwZDZiYWI2Mw==
- name: converger
  version: !binary |-
    MjUwYmQ0NTY3M2IwNzcwYzEyN2EyN2YzYmExZjFjOTg5OGVjOGM2MA==
  fingerprint: !binary |-
    MjUwYmQ0NTY3M2IwNzcwYzEyN2EyN2YzYmExZjFjOTg5OGVjOGM2MA==
  sha1: !binary |-
    ZTg3MDBlYmNjOTlhZWFmNWNjMjgwZmZkYjlkNTBlYzliNGVjZTg5ZQ==
- name: garden
  version: !binary |-
    NGQ2ZGFlMmQ5MDJmOTU2Y2Y3ODY0ZWYxOWM0ZGM0Yjc5MjZhOWM2ZA==
  fingerprint: !binary |-
    NGQ2ZGFlMmQ5MDJmOTU2Y2Y3ODY0ZWYxOWM0ZGM0Yjc5MjZhOWM2ZA==
  sha1: !binary |-
    MDFkYTcyY2EyNDgwZDVkZTI3OGJmODliNTczZDgwNjkzYWNkNzI1Nw==
- name: etcd
  version: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  fingerprint: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  sha1: !binary |-
    MzFiNDJiOTYwYzBkMWUwMDhkZTE4YmFlNDYxZDI5OTBkZjllNGZjZQ==
commit_hash: 17398a76
uncommitted_changes: true
name: diego
version: '0.460'
