---
packages:
- name: executor
  version: !binary |-
    NDA5YzUyNTNjZTY2MGIyNTZhOWZkZTc3MDQzMmNkMTkyYTcxYzU2Ng==
  sha1: !binary |-
    MGViZGU0ZmQwOTVlMjE2MTYzM2E2YTczOWIwM2I4ZmY0ODI5MzViMg==
  fingerprint: !binary |-
    NDA5YzUyNTNjZTY2MGIyNTZhOWZkZTc3MDQzMmNkMTkyYTcxYzU2Ng==
  dependencies:
  - golang
- name: stager
  version: !binary |-
    YWYwMDYxOWU0M2I5NGRiMmY0NDBjN2Y0MDVkNzM3NTU2OTRmY2ZkOQ==
  sha1: !binary |-
    NTQ0OGY1N2ViNTI4NjIxMGQxZjAzNTgwNWFlYjExNGYzZjIyNDkyMQ==
  fingerprint: !binary |-
    YWYwMDYxOWU0M2I5NGRiMmY0NDBjN2Y0MDVkNzM3NTU2OTRmY2ZkOQ==
  dependencies:
  - golang
- name: syslog_forwarder
  version: !binary |-
    OTVkZDcxNTI4NDU5YWU2MjFkZDhlODFhYzU5ZTViNWM4ZGE3NDdiNA==
  sha1: !binary |-
    ZTljYmE1OTRkNmRhNzJlMTJkNzZiZmYzOWI4ZjI1NWNjOGMwMTU2Ng==
  fingerprint: !binary |-
    OTVkZDcxNTI4NDU5YWU2MjFkZDhlODFhYzU5ZTViNWM4ZGE3NDdiNA==
  dependencies: []
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    ODNlZmQ2ZGE2OGYzMTFhZGFiYzg0OTMxOGU1NjcxMjczODU3YTdjZg==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: etcd
  version: !binary |-
    YWNjZmNhODlkNDZjMjExOTBiZWRhMmJjNDIxNzdjZTcwZDg1ODRjMA==
  sha1: !binary |-
    ZjRjOTBhOTY3MTY5MjA5ZmMzNzAwZWRjZmMzN2U4NzEwYWYyNDBkMw==
  fingerprint: !binary |-
    YWNjZmNhODlkNDZjMjExOTBiZWRhMmJjNDIxNzdjZTcwZDg1ODRjMA==
  dependencies:
  - golang
- name: nsync
  version: !binary |-
    NTkzYmRhNGYwMGMyNTk4YzFiOWY4MWFmMjk0NWU5MjVhNjhmZTY3Mw==
  sha1: !binary |-
    MTBmZDAwNjk0NzI0ZjRlOGE2MzVkODA4NzlmMjIyYWFiZTk4ODNhZQ==
  fingerprint: !binary |-
    NTkzYmRhNGYwMGMyNTk4YzFiOWY4MWFmMjk0NWU5MjVhNjhmZTY3Mw==
  dependencies:
  - golang
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MTUxMjA2NjY3ZmI0MjQzMTUzYjUwODA2ZTk3YjFmYjdkZTlhOTRjZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: runtime_metrics_server
  version: !binary |-
    ZmQyYzQ4OTI5MDgyYzk3ODc3OTNhNzZhZjc4ZTUzOWQxM2FmYjA2OA==
  sha1: !binary |-
    NDM1YjYzOTlkYWFkMGQzMDRjNGY1ZjUyYTVlMWI2YjZiMzUwYjRhNQ==
  fingerprint: !binary |-
    ZmQyYzQ4OTI5MDgyYzk3ODc3OTNhNzZhZjc4ZTUzOWQxM2FmYjA2OA==
  dependencies:
  - golang
- name: file_server
  version: !binary |-
    YjUwM2MwOTdjNjhmYTEyMmJiZDY3MjEzYmRkZThmMmM1YjliOGJlMw==
  sha1: !binary |-
    MjRiMmVmZTM5ODZkMzQwZDUzODVmZmM3MWJkOWI1ZWJjM2I4ZDdmNQ==
  fingerprint: !binary |-
    YjUwM2MwOTdjNjhmYTEyMmJiZDY3MjEzYmRkZThmMmM1YjliOGJlMw==
  dependencies:
  - golang
- name: route_emitter
  version: !binary |-
    ZDVkNjIwYWI2ZWNhNDE1NmM0ZTk4MmJhYjMwOTBmMzBmZjZmMzU1OA==
  sha1: !binary |-
    OGQyZDBlNGQzYTJiMTZiM2NlYTg0MWJmMTE0OTg3ZWM3OGVmNWEzMQ==
  fingerprint: !binary |-
    ZDVkNjIwYWI2ZWNhNDE1NmM0ZTk4MmJhYjMwOTBmMzBmZjZmMzU1OA==
  dependencies:
  - golang
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    NWIwZmZiYTAxMGIyM2RkMjFlZjIxZTdjMDM4NWQ0NjhhNWRhYTNiMw==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
- name: converger
  version: !binary |-
    MDE2NmQyYTllYzRiNDU5M2FjYTk4N2RhMDllMTQyMGZhY2E5YmZkMw==
  sha1: !binary |-
    OTM3OTUxMGViMmE4MWM0OGU0NzQ2Y2JlYzJhZjRiNzNkNWRlNzVlNg==
  fingerprint: !binary |-
    MDE2NmQyYTllYzRiNDU5M2FjYTk4N2RhMDllMTQyMGZhY2E5YmZkMw==
  dependencies:
  - golang
- name: linux-circus
  version: !binary |-
    MjVmNDQzNGQ3MjEyNWFlZTc3NzE1YTlkNWU1MjhhNzhlNzhmM2M5Yg==
  sha1: !binary |-
    YWRjMzljMmI5ZjYxZWYzMTMwOGI2OTkwZjJiMWE1ODNkYzA2YzdkNQ==
  fingerprint: !binary |-
    MjVmNDQzNGQ3MjEyNWFlZTc3NzE1YTlkNWU1MjhhNzhlNzhmM2M5Yg==
  dependencies:
  - golang
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    MGFhZmI4ZDU0M2M3YTExNDdhYzdkMGFhNmMzMzg1NDQyNjRiNjM1MQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: rep
  version: !binary |-
    OWQ5NGNhNTg5NGFlZTRlMDljNWRjZWVkNDllOGQwZWY0OTlmNjljNQ==
  sha1: !binary |-
    MjU0MjdmZDgyZDhkNTU4M2E0NDU1NGM0MWQ4ZmJmNzkyOTNjMjNlZA==
  fingerprint: !binary |-
    OWQ5NGNhNTg5NGFlZTRlMDljNWRjZWVkNDllOGQwZWY0OTlmNjljNQ==
  dependencies:
  - golang
- name: docker-circus
  version: !binary |-
    Njk2YmIxMjc3NmNiM2NiZjU5NjM5NDM4MzVmMDAxY2IzNWEyNDNlNA==
  sha1: !binary |-
    Y2EzZDE3NDFjMjM2NDgxMDg4N2RmNzViYTY5MWUzNDdkYzA1NWM2NA==
  fingerprint: !binary |-
    Njk2YmIxMjc3NmNiM2NiZjU5NjM5NDM4MzVmMDAxY2IzNWEyNDNlNA==
  dependencies:
  - golang
- name: tps
  version: !binary |-
    MjhkMTc2Nzk0MGFhMDlhYjA3N2JiOWYyNmRkYTczOWYxZGM3Y2JmZA==
  sha1: !binary |-
    NjI1MDg2ZjE3ZjMwMzQyZjc4OTYxZWVjNDc1NDg4NDM4ZmM2OTQ1ZQ==
  fingerprint: !binary |-
    MjhkMTc2Nzk0MGFhMDlhYjA3N2JiOWYyNmRkYTczOWYxZGM3Y2JmZA==
  dependencies:
  - golang
- name: etcd_metrics_server
  version: !binary |-
    MGVlNWEyNWZiZmRjMTYwY2Q3OTg2YTQ4MGY5OGY5MTRhNzI3YTc0NQ==
  sha1: !binary |-
    NTkxZjQ0ZjE5ZjNiZTY2OWFlOTc5MTNkOWY4MDAyMzVkZDc4ZWM5OA==
  fingerprint: !binary |-
    MGVlNWEyNWZiZmRjMTYwY2Q3OTg2YTQ4MGY5OGY5MTRhNzI3YTc0NQ==
  dependencies:
  - golang
- name: auctioneer
  version: !binary |-
    ZGI5NDU0YjA5MzU5ODJkY2UxM2NmMzc1YTY5ZTI2YmQ0NDQxODAyOA==
  sha1: !binary |-
    NTRhYTE3ZTFmNWRiNzMwMDI0OTkzZGExNzQ0ZjI1MjY2NjE0MGY1MA==
  fingerprint: !binary |-
    ZGI5NDU0YjA5MzU5ODJkY2UxM2NmMzc1YTY5ZTI2YmQ0NDQxODAyOA==
  dependencies:
  - golang
- name: warden-linux
  version: !binary |-
    NTg2N2Q3NzljMmQ1MGYxMTgyZWUwZjAyZDZhMmU4MzBkODQyOGEzOQ==
  sha1: !binary |-
    YTU3OTY4MDQ3NjZlYzM0NDkxY2ZiYmQ4NTM3ZmEwODVjYTk0NWNiZQ==
  fingerprint: !binary |-
    NTg2N2Q3NzljMmQ1MGYxMTgyZWUwZjAyZDZhMmU4MzBkODQyOGEzOQ==
  dependencies:
  - golang
- name: rootfs_lucid64
  version: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  sha1: !binary |-
    ZTE1M2YwMzkxNTM2NTZmNjYyNzdkNjAxMDAyMTA1NjRjODY1ZmQzNg==
  fingerprint: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  dependencies: []
jobs:
- name: executor
  version: !binary |-
    NmE2MzI3NzE4NmIxOWExOTE1NmU1Y2VjZGEwMjZiOTA3YWJiMmNmNw==
  fingerprint: !binary |-
    NmE2MzI3NzE4NmIxOWExOTE1NmU1Y2VjZGEwMjZiOTA3YWJiMmNmNw==
  sha1: !binary |-
    YThmMmYyNWE5MjBjM2Q0YzBmZGE0YzZjZTIwNjZjNTZhZDcxMTU4NQ==
- name: stager
  version: !binary |-
    N2Y0ZjMwNmM1YjVhMmZlMzg2MjFhZDEyNzUyMWM5MDhkOWY5ZjhiNw==
  fingerprint: !binary |-
    N2Y0ZjMwNmM1YjVhMmZlMzg2MjFhZDEyNzUyMWM5MDhkOWY5ZjhiNw==
  sha1: !binary |-
    NjE1NTZlZmQ3YjU4NzI1ZWMxOWFiYWZhY2NkZjhlYmM2ZTAxNTY0MQ==
- name: etcd
  version: !binary |-
    OTc4N2NlZGMxYWFiMjYxMDc2NWU4Y2E5MzM4OWIxMDg1ZmE1NTkzMw==
  fingerprint: !binary |-
    OTc4N2NlZGMxYWFiMjYxMDc2NWU4Y2E5MzM4OWIxMDg1ZmE1NTkzMw==
  sha1: !binary |-
    ZDQ3OGQ1YzY0MTFmODBhMWYwMWZhMGRhZGUwMWY5NTk5ZDA2ZmNkMQ==
- name: nsync
  version: !binary |-
    ZGMzMWE5YWQyODFjYWE2ZDU1NGUwNGI1N2QwMmYwZjNlNDczMDY5Mw==
  fingerprint: !binary |-
    ZGMzMWE5YWQyODFjYWE2ZDU1NGUwNGI1N2QwMmYwZjNlNDczMDY5Mw==
  sha1: !binary |-
    NTJlNWQ5MDYwZmNlMDA4Y2JmODJkZjE1MTc1NmM4OTM0NWIwNDMzMQ==
- name: runtime_metrics_server
  version: !binary |-
    MDIwMmQ3OTlmOTM1YjZhMjUxOTVkNzkwY2IyYjZkNGNjMWY0M2NjOA==
  fingerprint: !binary |-
    MDIwMmQ3OTlmOTM1YjZhMjUxOTVkNzkwY2IyYjZkNGNjMWY0M2NjOA==
  sha1: !binary |-
    MWU5YjMzZmEwNDcyNjI3NmEyZjZlNTQ0ZDRlZTA3YjJmYjI0NmY4Nw==
- name: file_server
  version: !binary |-
    ZWViYTUyZjRjZjkzZGU5Yzg1ZmJlMjQyY2I0ZTJkMTE3YmNjNWMzZQ==
  fingerprint: !binary |-
    ZWViYTUyZjRjZjkzZGU5Yzg1ZmJlMjQyY2I0ZTJkMTE3YmNjNWMzZQ==
  sha1: !binary |-
    OThlYmIzZjg4NzFlNDMzMDRjMmQ1YzhmZjUzNTkxMjgwODZmNmM0YQ==
- name: route_emitter
  version: !binary |-
    ZmNmNzhiN2E2Mzk3YmU1YmQ3NTI0MjViNDU2MzJiZDAxODViMjdiYw==
  fingerprint: !binary |-
    ZmNmNzhiN2E2Mzk3YmU1YmQ3NTI0MjViNDU2MzJiZDAxODViMjdiYw==
  sha1: !binary |-
    MzM4OTI0YTAwMGU5Nzc1YzQ1MmQxOWM4MWZlZTM1MzQxOTA3OTk4ZA==
- name: converger
  version: !binary |-
    MjQyN2YzNGQ1OWRjOGI5N2ZiMWY4NTgzNWFhZGQ1YmY1YjYxMDA3Nw==
  fingerprint: !binary |-
    MjQyN2YzNGQ1OWRjOGI5N2ZiMWY4NTgzNWFhZGQ1YmY1YjYxMDA3Nw==
  sha1: !binary |-
    NjJmZDBkMjJmMzhmOWVmMWNjNTA2ODA3NzA5Y2Q2NGNjNDliNDNmNA==
- name: rep
  version: !binary |-
    MGU3ZjczYmYxNWZkZGYyYTBlYmMwNDZjMjdiOTdkMDgwNDhiN2Q0ZA==
  fingerprint: !binary |-
    MGU3ZjczYmYxNWZkZGYyYTBlYmMwNDZjMjdiOTdkMDgwNDhiN2Q0ZA==
  sha1: !binary |-
    OGMxNGFjMTgyYWE1OTRhNzk1MzEwNTYwMzJjMmQyMzEzZTAxMDYzOA==
- name: warden
  version: !binary |-
    NjdmNmU5OTk2YWJhZjE5MTBhN2QyMDg2NTE5ZmIzNzA2YzE0ZWYzZA==
  fingerprint: !binary |-
    NjdmNmU5OTk2YWJhZjE5MTBhN2QyMDg2NTE5ZmIzNzA2YzE0ZWYzZA==
  sha1: !binary |-
    ODFjNjQzNjljYTgxMTY2OWEwNDEzYzU4NGMwYzYwYTA3NzJjOTQ1ZA==
- name: tps
  version: !binary |-
    Y2E3ODEyYjc0YmQwZmU4MjE3NTIzMzliNTA0NGQzN2UxN2VmYjllMg==
  fingerprint: !binary |-
    Y2E3ODEyYjc0YmQwZmU4MjE3NTIzMzliNTA0NGQzN2UxN2VmYjllMg==
  sha1: !binary |-
    ZDEzMDNhYzU2ZjVjZGI4ZjI5ZjYyZDhjZDlhZjI4YTZhMWUwNWZiZA==
- name: etcd_metrics_server
  version: !binary |-
    NDE0ZGRjYzFkM2MzYzQxODMzYjVkOTdhN2QzYmZiZGUzM2QzZDVjNQ==
  fingerprint: !binary |-
    NDE0ZGRjYzFkM2MzYzQxODMzYjVkOTdhN2QzYmZiZGUzM2QzZDVjNQ==
  sha1: !binary |-
    OTdkOGY3NGYzZmEyZDMwMzQ1Njg1OGU5ZjlmMWM3NTQ0OTdjMTZlYQ==
- name: auctioneer
  version: !binary |-
    YTdmMTdmZDUzMTkwYzE1NTFjMzBlZTYzNDIzOWNkYWVhZWEyNmE4NA==
  fingerprint: !binary |-
    YTdmMTdmZDUzMTkwYzE1NTFjMzBlZTYzNDIzOWNkYWVhZWEyNmE4NA==
  sha1: !binary |-
    NGY0ZmI0MjM3NDY2OTA0ZWU3MDY1MzE0NTk4MzNlOWQ4MTc5OTU2NA==
commit_hash: 5fdd46f7
uncommitted_changes: true
name: diego
version: '0.352'
