---
packages:
- name: nsync
  version: !binary |-
    ODQwZDkyZGZhYjhkZWYxODdiNmNiOTIxMmJlNzNmM2NhNTk2MThhZA==
  sha1: !binary |-
    ODEwMTEzYzFhMGIzNmJmM2ZmYTQzOWFjZjRmOGEyYTUxYTM2YmI5ZQ==
  fingerprint: !binary |-
    ODQwZDkyZGZhYjhkZWYxODdiNmNiOTIxMmJlNzNmM2NhNTk2MThhZA==
  dependencies:
  - golang
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    NWIwZmZiYTAxMGIyM2RkMjFlZjIxZTdjMDM4NWQ0NjhhNWRhYTNiMw==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
- name: rep
  version: !binary |-
    YzkyODkwOGJmZWIyOGRjMDkxODk2YjZjOWIwMDQwYWE0MWIyZTQxZg==
  sha1: !binary |-
    MDdjNTc2ZDk2NjViMjJhYjljMzNmMjk1MzhiODk5MTIwNjJkMzU4NA==
  fingerprint: !binary |-
    YzkyODkwOGJmZWIyOGRjMDkxODk2YjZjOWIwMDQwYWE0MWIyZTQxZg==
  dependencies:
  - golang
- name: acceptance-tests
  version: !binary |-
    OTAzMTAzZmQwMzFmMTU1ZmM1Mjk3NDE3OWI4ZTlkMWNhMjk2YWI4OQ==
  sha1: !binary |-
    MDE4MjA4MWJkYjYzOWIwYmMyZTNjNzhlZWRhMGE4ODVjMGE5NmU1YQ==
  fingerprint: !binary |-
    OTAzMTAzZmQwMzFmMTU1ZmM1Mjk3NDE3OWI4ZTlkMWNhMjk2YWI4OQ==
  dependencies:
  - golang
- name: route_emitter
  version: !binary |-
    YmVmNGIzZTdjN2QyNDBiNWQzZWNlNjlkY2M3Y2VjNDE3YzZlNGRlNw==
  sha1: !binary |-
    NjljNTE3ODU5YjkzNzlkNWViMDQ0M2UwNDVhYWUyOWFiMWIyMGM2OA==
  fingerprint: !binary |-
    YmVmNGIzZTdjN2QyNDBiNWQzZWNlNjlkY2M3Y2VjNDE3YzZlNGRlNw==
  dependencies:
  - golang
- name: auctioneer
  version: !binary |-
    Y2IyYzU2ZjhhZTRiOWZkYWJjMDI3YTM3NTU5OWJlYmVlODMyZGYyYQ==
  sha1: !binary |-
    NjU1YWRmM2E1MGE2OWU4NzRhYmQ1YzNlODY4MmEyZWMyNWM0NTQ4Mw==
  fingerprint: !binary |-
    Y2IyYzU2ZjhhZTRiOWZkYWJjMDI3YTM3NTU5OWJlYmVlODMyZGYyYQ==
  dependencies:
  - golang
- name: rootfs_lucid64
  version: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  sha1: !binary |-
    ZTE1M2YwMzkxNTM2NTZmNjYyNzdkNjAxMDAyMTA1NjRjODY1ZmQzNg==
  fingerprint: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  dependencies: []
- name: tps
  version: !binary |-
    Y2U5ODgyNWQxYjAxNjc3MTFiNjlkZGZmZDk3N2M5ZWI2NGZhYTYwNw==
  sha1: !binary |-
    YzZkODJiNmMwMDhlYTZhOGM2MTY5ZWY1NTljNzc2OTMzZmY5OTU4Mg==
  fingerprint: !binary |-
    Y2U5ODgyNWQxYjAxNjc3MTFiNjlkZGZmZDk3N2M5ZWI2NGZhYTYwNw==
  dependencies:
  - golang
- name: linux-circus
  version: !binary |-
    ZjJiNGI5YmU5NWY2OTIwZWE1NjZlM2YyZjA5YjljYjY1ZmI2YjA2MQ==
  sha1: !binary |-
    NGE5Mjg4YmQwMDE5NjgxNzU1MGVhMTAwNmY1MzI4YTFkNzMzY2IyZA==
  fingerprint: !binary |-
    ZjJiNGI5YmU5NWY2OTIwZWE1NjZlM2YyZjA5YjljYjY1ZmI2YjA2MQ==
  dependencies:
  - golang
- name: docker-circus
  version: !binary |-
    MWZiZDJjNjhkYTc4NTY5OTRiOWMzZTY4YmQyNjRmOTIxZDE0OWI1OQ==
  sha1: !binary |-
    NTdmNTYxMTlkNDllOTJiMjNiOGFjNzRmNDExZDIzMTA1NmYwOGVlNw==
  fingerprint: !binary |-
    MWZiZDJjNjhkYTc4NTY5OTRiOWMzZTY4YmQyNjRmOTIxZDE0OWI1OQ==
  dependencies:
  - golang
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    MGFhZmI4ZDU0M2M3YTExNDdhYzdkMGFhNmMzMzg1NDQyNjRiNjM1MQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: runtime_metrics_server
  version: !binary |-
    ZThiODZmODc5ZDBkYWEwYjMxYTExYTI5OWY5NTI1MTI0YTY4NGQ4OA==
  sha1: !binary |-
    ZDE4MTExNWMzY2E0MzAxNzhkYWVmZWIwYWZjYTNhNzExYWI4NDc5ZQ==
  fingerprint: !binary |-
    ZThiODZmODc5ZDBkYWEwYjMxYTExYTI5OWY5NTI1MTI0YTY4NGQ4OA==
  dependencies:
  - golang
- name: executor
  version: !binary |-
    ZWE1MTI2MGNjZDhmMjdjMjQ5Zjg0NDY2ZGU3YTQ3Y2RmZjk4ZGY0NA==
  sha1: !binary |-
    MzRkOTMwYzk4YWEzNzMzNDk5OWY0NGZmYzhhN2U0ZjQzYjEzYzkwOQ==
  fingerprint: !binary |-
    ZWE1MTI2MGNjZDhmMjdjMjQ5Zjg0NDY2ZGU3YTQ3Y2RmZjk4ZGY0NA==
  dependencies:
  - golang
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MTUxMjA2NjY3ZmI0MjQzMTUzYjUwODA2ZTk3YjFmYjdkZTlhOTRjZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: converger
  version: !binary |-
    ZTliZWQ5ZWQyNjY0YWI3YWFlYmU5ZjlhZjQxYmQwOTNlMmQwMDgzNw==
  sha1: !binary |-
    OGNhNGI0ODEzMWI1ZjcyNjAzOTlhOTUzMTA0YTBjNTJlYjIyYmQzYw==
  fingerprint: !binary |-
    ZTliZWQ5ZWQyNjY0YWI3YWFlYmU5ZjlhZjQxYmQwOTNlMmQwMDgzNw==
  dependencies:
  - golang
- name: etcd_metrics_server
  version: !binary |-
    YmU5ODcyNTIxZjhhMDM2ZTY0MzkzZGQ2M2M5Y2FkOWU2M2EyOWZkMA==
  sha1: !binary |-
    MjNmMjQ0NWZkZjY0OTI1YWRmNzNkYTI3NjdlZmRjNTJmZGNlNDRhMQ==
  fingerprint: !binary |-
    YmU5ODcyNTIxZjhhMDM2ZTY0MzkzZGQ2M2M5Y2FkOWU2M2EyOWZkMA==
  dependencies:
  - golang
- name: smoke-tests
  version: !binary |-
    YzZhYjAwN2JjYTdjNzA3ODgwNzVlOWMwMDQ1MWYwNzdiOTBhZDBkZg==
  sha1: !binary |-
    YTA2ODdjYTAxNWEzN2YzM2E5OTBlNmJhZDJjNTM3ZWQwY2FkMjQwMA==
  fingerprint: !binary |-
    YzZhYjAwN2JjYTdjNzA3ODgwNzVlOWMwMDQ1MWYwNzdiOTBhZDBkZg==
  dependencies:
  - golang
- name: garden-linux
  version: !binary |-
    OWI1ZDUzN2UzYWUyZjY0NDY3MGIwZDlhNmEzMWEwNTM4ZDdjNWUwMg==
  sha1: !binary |-
    ZTY4NmI4YTZhMWVmZjI2MDBjZDNmODRhMTljZDY2NDY1MzAxY2Q5YQ==
  fingerprint: !binary |-
    OWI1ZDUzN2UzYWUyZjY0NDY3MGIwZDlhNmEzMWEwNTM4ZDdjNWUwMg==
  dependencies:
  - golang
- name: etcd
  version: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  sha1: !binary |-
    NjdlMWM4Yjk1YzhiNWMzMmIxZjg5ZjNjMjc1YmQ5ZjYxNmExZDc2Yw==
  fingerprint: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  dependencies:
  - golang
- name: file_server
  version: !binary |-
    ZmNhYThjMjEyYjE0NTNmMDc3YjBkYzU5NjQ0ODIyNjRjZDhiZjVjOA==
  sha1: !binary |-
    MjQ4NmE1ZWM5NTEzNWNlNjIxZDY1YmEwMmQwY2U2YTc2Mzc1ODc0MA==
  fingerprint: !binary |-
    ZmNhYThjMjEyYjE0NTNmMDc3YjBkYzU5NjQ0ODIyNjRjZDhiZjVjOA==
  dependencies:
  - golang
- name: cf-cli
  version: !binary |-
    OTRhNzlmYmFlODdmN2E4ZWMzMDA0MTYyYjFjNTlkMTNhZDY5NzU4OA==
  sha1: !binary |-
    YTM2Mzc1NTkzMTE4YTkxODQ0NTY0ZDY1YjA0YzhkYjk1NzUzYjIwYQ==
  fingerprint: !binary |-
    OTRhNzlmYmFlODdmN2E4ZWMzMDA0MTYyYjFjNTlkMTNhZDY5NzU4OA==
  dependencies: []
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    ODNlZmQ2ZGE2OGYzMTFhZGFiYzg0OTMxOGU1NjcxMjczODU3YTdjZg==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: stager
  version: !binary |-
    ZTc3OTljMWYxYjhmYzIxMjA1NGYxOTZhMTA1ZTc2MzVlNjI4MTdiNg==
  sha1: !binary |-
    YWM4M2JjY2MyODQzZmY2MTBjOTAzZmMwMTE3YmMzNDE2YzRmZjhmNQ==
  fingerprint: !binary |-
    ZTc3OTljMWYxYjhmYzIxMjA1NGYxOTZhMTA1ZTc2MzVlNjI4MTdiNg==
  dependencies:
  - golang
jobs:
- name: nsync
  version: !binary |-
    MDZlOTJkOGY3ZGU3MGU4YzlkZWM1NTdhNDVkODAzOWViZjBhN2Y1ZQ==
  fingerprint: !binary |-
    MDZlOTJkOGY3ZGU3MGU4YzlkZWM1NTdhNDVkODAzOWViZjBhN2Y1ZQ==
  sha1: !binary |-
    NDkxODVmMzVmNmE2MDcxZmNhZTk1MDhhN2MzZWY1MmYwZDZiYWI2Mw==
- name: rep
  version: !binary |-
    MTg5YjExOTJkOGIwYTM5NzExZmEzNmNlNGUyZTQxODRhOGI4NjM2Zg==
  fingerprint: !binary |-
    MTg5YjExOTJkOGIwYTM5NzExZmEzNmNlNGUyZTQxODRhOGI4NjM2Zg==
  sha1: !binary |-
    NzkyNzJjMDkzZmVlY2VmZjNhZTM4ODA5NDQxY2VlNzcwOGEwZGRkMw==
- name: acceptance-tests
  version: !binary |-
    MTI0YjA1MDYyYmFlYWJkNGUyNzMyODZjZjE2N2Q2ZTI0NmY3MWJiNA==
  fingerprint: !binary |-
    MTI0YjA1MDYyYmFlYWJkNGUyNzMyODZjZjE2N2Q2ZTI0NmY3MWJiNA==
  sha1: !binary |-
    OTgzYjdiZTljNmEyZjBlY2IyYjNlOWFiNDBiMzQ5ZTA1YjRiNDFlNw==
- name: route_emitter
  version: !binary |-
    OGI2ZjJhOTAyYjc2NmNhMzRkZDhmNDM0YjYwZTRiMTAyNGFkZGNlNA==
  fingerprint: !binary |-
    OGI2ZjJhOTAyYjc2NmNhMzRkZDhmNDM0YjYwZTRiMTAyNGFkZGNlNA==
  sha1: !binary |-
    YmM0YWRmZTA3MjQwYTA2ODU0MDMzZWRhYTEyNjc3OGZlZGE5MzM3MA==
- name: auctioneer
  version: !binary |-
    N2M4MjM2MDg4ZmJhZTQzZTczNzhmMzY4MzYzN2ZlNjFiYTBiYzg1Yw==
  fingerprint: !binary |-
    N2M4MjM2MDg4ZmJhZTQzZTczNzhmMzY4MzYzN2ZlNjFiYTBiYzg1Yw==
  sha1: !binary |-
    MjNmMDhmOWIxZTcxZjU1OWRkODZlZTMxN2U2MWJiNDc1Nzg2YzkxYw==
- name: tps
  version: !binary |-
    YThlYjVhOWFhOGU5YWI4YTkxNmZlYzI4MzNhMGQwODljMzA5YzQyNQ==
  fingerprint: !binary |-
    YThlYjVhOWFhOGU5YWI4YTkxNmZlYzI4MzNhMGQwODljMzA5YzQyNQ==
  sha1: !binary |-
    ZTRmZDI2NmYwNDBiZDU0YTc1MjNjZDc5NTU0ZDFlOWE0NjY5ZGNhYw==
- name: runtime_metrics_server
  version: !binary |-
    OThhNTAyNDUwZTczMTk1MDE4NTJiYjc2NWU0OThiZGI2NDYxNTVlNQ==
  fingerprint: !binary |-
    OThhNTAyNDUwZTczMTk1MDE4NTJiYjc2NWU0OThiZGI2NDYxNTVlNQ==
  sha1: !binary |-
    Yjk3ZjM0OTA4MWNkZjMwMjcyMThjZTJmYzRjZThlYmU1YjY2YWE3Yg==
- name: executor
  version: !binary |-
    MmNmNGU0NTQwNzBkNzg1Mzk1YTM4Nzg3Y2RjNWE0ZDE4ZDU3MDlmMw==
  fingerprint: !binary |-
    MmNmNGU0NTQwNzBkNzg1Mzk1YTM4Nzg3Y2RjNWE0ZDE4ZDU3MDlmMw==
  sha1: !binary |-
    ZWJkZDJkOWZlZGI3ZTlmNjc2MjFmMTZlOTY0NzY1MDViZTQ0M2E1Mw==
- name: converger
  version: !binary |-
    MjUwYmQ0NTY3M2IwNzcwYzEyN2EyN2YzYmExZjFjOTg5OGVjOGM2MA==
  fingerprint: !binary |-
    MjUwYmQ0NTY3M2IwNzcwYzEyN2EyN2YzYmExZjFjOTg5OGVjOGM2MA==
  sha1: !binary |-
    ZTg3MDBlYmNjOTlhZWFmNWNjMjgwZmZkYjlkNTBlYzliNGVjZTg5ZQ==
- name: etcd_metrics_server
  version: !binary |-
    OGU4NzYzY2Y0ZDY0ZjBjYTEwM2UyOGNiOWYwMTliNGIyYzQwODFlOQ==
  fingerprint: !binary |-
    OGU4NzYzY2Y0ZDY0ZjBjYTEwM2UyOGNiOWYwMTliNGIyYzQwODFlOQ==
  sha1: !binary |-
    YjA2NGNkMmYxODhkZjZlODMyZDIzNTNmNzkwM2EwYmUwOWRhMmQwZg==
- name: smoke-tests
  version: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  fingerprint: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  sha1: !binary |-
    YjQxNDIyZTJmN2I0NjIyMzA5NTdkOWZlZGI5MDk0MDBlNmEzOTllNg==
- name: etcd
  version: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  fingerprint: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  sha1: !binary |-
    MzFiNDJiOTYwYzBkMWUwMDhkZTE4YmFlNDYxZDI5OTBkZjllNGZjZQ==
- name: file_server
  version: !binary |-
    Y2E1NDc0NWU5NDJmOGU4NDM5ODQ1NjNiYWEyOWNiZTViMTNiMTFhNw==
  fingerprint: !binary |-
    Y2E1NDc0NWU5NDJmOGU4NDM5ODQ1NjNiYWEyOWNiZTViMTNiMTFhNw==
  sha1: !binary |-
    MTFiNzdiMTZiMjhkOTQxNDQ0MzM4ZjcwZWExMjRlNjIyODJiZDJmNA==
- name: garden
  version: !binary |-
    NGQ2ZGFlMmQ5MDJmOTU2Y2Y3ODY0ZWYxOWM0ZGM0Yjc5MjZhOWM2ZA==
  fingerprint: !binary |-
    NGQ2ZGFlMmQ5MDJmOTU2Y2Y3ODY0ZWYxOWM0ZGM0Yjc5MjZhOWM2ZA==
  sha1: !binary |-
    MDFkYTcyY2EyNDgwZDVkZTI3OGJmODliNTczZDgwNjkzYWNkNzI1Nw==
- name: stager
  version: !binary |-
    YjgwYjc3ZTQ3MmI3ODcxYmM5ZDI4YTM1YmEwMTY3ZTM3MGQxODVhMQ==
  fingerprint: !binary |-
    YjgwYjc3ZTQ3MmI3ODcxYmM5ZDI4YTM1YmEwMTY3ZTM3MGQxODVhMQ==
  sha1: !binary |-
    ZjljMmVlMzdhYzRmZThjMjdlMTg1NzI3NzhmZWUwYmUxYzdkNjZiMg==
commit_hash: d30b37d4
uncommitted_changes: true
name: diego
version: '0.462'
