---
packages:
- name: etcd
  version: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  sha1: !binary |-
    NjdlMWM4Yjk1YzhiNWMzMmIxZjg5ZjNjMjc1YmQ5ZjYxNmExZDc2Yw==
  fingerprint: !binary |-
    MjZhMWJiN2M4YTUzMjY0MTI3NWVhMzBlOGFlMjE2MTUwYjZkYzAzMw==
  dependencies:
  - golang
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    ODNlZmQ2ZGE2OGYzMTFhZGFiYzg0OTMxOGU1NjcxMjczODU3YTdjZg==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: stager
  version: !binary |-
    MzA1NjEyYjE5ZmUzMjQ5OTBmNGIzNjY3OWJkOTYzZDM4OTAzMDQ5ZA==
  sha1: !binary |-
    Y2FjNmM5NTIyMzE3ZGM3NWJhYjU0ZWNhMWQ3ZGJkZmZhM2Q0ZjQ3ZQ==
  fingerprint: !binary |-
    MzA1NjEyYjE5ZmUzMjQ5OTBmNGIzNjY3OWJkOTYzZDM4OTAzMDQ5ZA==
  dependencies:
  - golang
- name: rep
  version: !binary |-
    N2UzNGNjMzk0OTVmOWZjYTU1MzIyMGI0ZTU3YmE4YmUzYTY2ZTM4OQ==
  sha1: !binary |-
    MDA2MTZjY2U1YjUwNGE0YWQ1OTdjNjYwMzBjYWEzYWNiM2U5NmEzYg==
  fingerprint: !binary |-
    N2UzNGNjMzk0OTVmOWZjYTU1MzIyMGI0ZTU3YmE4YmUzYTY2ZTM4OQ==
  dependencies:
  - golang
- name: tps
  version: !binary |-
    MDFkNzc4NWExNmZjOTc5YjljNGU3ZDRlMzIwZWE1ZDMxZDE4NWM2Yg==
  sha1: !binary |-
    YzQ1NjBkMTY5ZWQ5ZWVmNzUyMDY5ZjM4ZWY1MmM3MjcyY2RlMTUzNw==
  fingerprint: !binary |-
    MDFkNzc4NWExNmZjOTc5YjljNGU3ZDRlMzIwZWE1ZDMxZDE4NWM2Yg==
  dependencies:
  - golang
- name: file_server
  version: !binary |-
    ZmY5MjkzODA3ZDQ0ZDRhZjg1YWYzMWMzMjlhNzMwYjYyZjdiYTQ2NQ==
  sha1: !binary |-
    YTMyODRhMThiMjRhZWFkOWU5NWY2MGJiZjZhNTc5NGNjMWRmNTVjNg==
  fingerprint: !binary |-
    ZmY5MjkzODA3ZDQ0ZDRhZjg1YWYzMWMzMjlhNzMwYjYyZjdiYTQ2NQ==
  dependencies:
  - golang
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    MGFhZmI4ZDU0M2M3YTExNDdhYzdkMGFhNmMzMzg1NDQyNjRiNjM1MQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: nsync
  version: !binary |-
    ZWQ1MDQ1MWMzZmU0ZDM3NWFjNjlmMWExMDQ2OGRjMjUyYzY3ODJmMg==
  sha1: !binary |-
    MGM4ZDU1MzYxNmZhNGQ0YmU2N2ZiM2MwMjcyM2IzOTNjNWI5Zjk4Yw==
  fingerprint: !binary |-
    ZWQ1MDQ1MWMzZmU0ZDM3NWFjNjlmMWExMDQ2OGRjMjUyYzY3ODJmMg==
  dependencies:
  - golang
- name: runtime_metrics_server
  version: !binary |-
    MmEwOWU1MGQ2ZWQ3NWNhYWU4OTk1MjliZGE1NTMxMmFlMWRmNDRhMA==
  sha1: !binary |-
    MTcwNTIyOTYzYzI3YzE0NDk4ZTdmMjk5ODIyMDgxNmE5ZDA1Yjk3ZA==
  fingerprint: !binary |-
    MmEwOWU1MGQ2ZWQ3NWNhYWU4OTk1MjliZGE1NTMxMmFlMWRmNDRhMA==
  dependencies:
  - golang
- name: cf-cli
  version: !binary |-
    OTRhNzlmYmFlODdmN2E4ZWMzMDA0MTYyYjFjNTlkMTNhZDY5NzU4OA==
  sha1: !binary |-
    YTM2Mzc1NTkzMTE4YTkxODQ0NTY0ZDY1YjA0YzhkYjk1NzUzYjIwYQ==
  fingerprint: !binary |-
    OTRhNzlmYmFlODdmN2E4ZWMzMDA0MTYyYjFjNTlkMTNhZDY5NzU4OA==
  dependencies: []
- name: etcd_metrics_server
  version: !binary |-
    MmYyM2E2MTk2ZmMxMjk0ZDA0NDc3MWQyZmIyNzRiNTMxYzIzN2UzYQ==
  sha1: !binary |-
    Zjg3NWIxMzU5ZWI4ZDU4ODA4OWZlNTNmNDExYjI4YjJlNWYxN2NhYQ==
  fingerprint: !binary |-
    MmYyM2E2MTk2ZmMxMjk0ZDA0NDc3MWQyZmIyNzRiNTMxYzIzN2UzYQ==
  dependencies:
  - golang
- name: rootfs_lucid64
  version: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  sha1: !binary |-
    NGUyOTNiNWQwMjBkNmRiZGVhN2FmMjZhYmUzZTRmMDg2NGJjNjFmMg==
  fingerprint: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  dependencies: []
- name: auctioneer
  version: !binary |-
    ZWY3NTU3ZGFkY2NjOWRjN2Q5NDY3ZGY5NzEyZDZhOGVjYWEwYmQyZA==
  sha1: !binary |-
    MDUwMDUyMmIzMGUxNzcxYmVkYjVkZWRjMzFlZTM5YWNkZTc2NTQ2Mg==
  fingerprint: !binary |-
    ZWY3NTU3ZGFkY2NjOWRjN2Q5NDY3ZGY5NzEyZDZhOGVjYWEwYmQyZA==
  dependencies:
  - golang
- name: garden-linux
  version: !binary |-
    NDQ3YTM3MTA0NjhmZGU0YTVmMzk1OWZhMDE1Y2YzMjkxODk5M2FkOA==
  sha1: !binary |-
    ZjZlNDM2Zjk1Mjc2ZjdmYjBmYThmMmE1Y2Q3NDljYWM4Yjk1MzBhYg==
  fingerprint: !binary |-
    NDQ3YTM3MTA0NjhmZGU0YTVmMzk1OWZhMDE1Y2YzMjkxODk5M2FkOA==
  dependencies:
  - golang
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MTUxMjA2NjY3ZmI0MjQzMTUzYjUwODA2ZTk3YjFmYjdkZTlhOTRjZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: converger
  version: !binary |-
    MDk1N2UwNjMyNjhjOTRlMTMzNmVkMzZiNzczN2VjNTk2MjdlNDEyMw==
  sha1: !binary |-
    ZmI0ODY0NDVlNzNiYjM0ODExYzkxMTAyNTU2ODJiOWJlMDg3MjI1Zg==
  fingerprint: !binary |-
    MDk1N2UwNjMyNjhjOTRlMTMzNmVkMzZiNzczN2VjNTk2MjdlNDEyMw==
  dependencies:
  - golang
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    NWIwZmZiYTAxMGIyM2RkMjFlZjIxZTdjMDM4NWQ0NjhhNWRhYTNiMw==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
- name: acceptance-tests
  version: !binary |-
    OGZjYzVlMzFlMjI4YzcyMzE2NzRhODJjZjJmYzBjOGE3ZWU5MTYzMA==
  sha1: !binary |-
    NTRiMjYyNzEzMTM3YTM4MzBlNDZjMzgzMTgxYmY5MjcwNDE3MTg0OQ==
  fingerprint: !binary |-
    OGZjYzVlMzFlMjI4YzcyMzE2NzRhODJjZjJmYzBjOGE3ZWU5MTYzMA==
  dependencies:
  - golang
- name: executor
  version: !binary |-
    NTMzMzQ4OTk2Njk2MWNjZmM1Y2RlZjEzMTQ2ZDUwODhkYjUxYWEzYw==
  sha1: !binary |-
    ZDI5ZWEwOWVkYjExYjcyODcxNjhlMmYzMjk2MjE4YWJlZWE3NTNjZA==
  fingerprint: !binary |-
    NTMzMzQ4OTk2Njk2MWNjZmM1Y2RlZjEzMTQ2ZDUwODhkYjUxYWEzYw==
  dependencies:
  - golang
- name: route_emitter
  version: !binary |-
    OThhMzUwMWFjMGQ3NzBkZTRiNDgwNzY4YjI4NGQwY2ZmNDQ3OWUwNA==
  sha1: !binary |-
    MzVhNTE2OTM0MTMwY2I1ZTY4OTEzY2I2M2Y0MmQ3YTZlZjk2ZGY5Zg==
  fingerprint: !binary |-
    OThhMzUwMWFjMGQ3NzBkZTRiNDgwNzY4YjI4NGQwY2ZmNDQ3OWUwNA==
  dependencies:
  - golang
- name: linux-circus
  version: !binary |-
    NmRjNmJjZjZkM2MxMTFjNmQzZDdkZTdiZjhjYzE1OGU5ZGM3YTQxMQ==
  sha1: !binary |-
    NDk0NmI4N2IyY2NlMjZkMGU3MmUzN2U5NjhkZmQwMjI0ZDlkMTg4Mw==
  fingerprint: !binary |-
    NmRjNmJjZjZkM2MxMTFjNmQzZDdkZTdiZjhjYzE1OGU5ZGM3YTQxMQ==
  dependencies:
  - golang
- name: docker-circus
  version: !binary |-
    MzE2MjBkZWQ2YzFjYjAxNmU1MTYxMWFiZjRlMzg5MTI3ZThjM2MyYw==
  sha1: !binary |-
    ZTFiNDQ0YmIwNmRjZjFlZGYxNjMwZTE5NzA4MGFlNzNjMTk4YjY5Yg==
  fingerprint: !binary |-
    MzE2MjBkZWQ2YzFjYjAxNmU1MTYxMWFiZjRlMzg5MTI3ZThjM2MyYw==
  dependencies:
  - golang
- name: smoke-tests
  version: !binary |-
    ZDQwODdkN2Q4NWNmMDQzZDIxMTk5MGJmZWRhNTZlMTRjNmI0YjZiYw==
  sha1: !binary |-
    OTQ4YzIzYjE0MzM3ZmYzNzNiMDA4Yjg5ZGRhOTFkZTNjMmJhYzliMA==
  fingerprint: !binary |-
    ZDQwODdkN2Q4NWNmMDQzZDIxMTk5MGJmZWRhNTZlMTRjNmI0YjZiYw==
  dependencies:
  - golang
jobs:
- name: etcd
  version: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  fingerprint: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  sha1: !binary |-
    MzFiNDJiOTYwYzBkMWUwMDhkZTE4YmFlNDYxZDI5OTBkZjllNGZjZQ==
- name: stager
  version: !binary |-
    YjgwYjc3ZTQ3MmI3ODcxYmM5ZDI4YTM1YmEwMTY3ZTM3MGQxODVhMQ==
  fingerprint: !binary |-
    YjgwYjc3ZTQ3MmI3ODcxYmM5ZDI4YTM1YmEwMTY3ZTM3MGQxODVhMQ==
  sha1: !binary |-
    ZjljMmVlMzdhYzRmZThjMjdlMTg1NzI3NzhmZWUwYmUxYzdkNjZiMg==
- name: rep
  version: !binary |-
    MTg5YjExOTJkOGIwYTM5NzExZmEzNmNlNGUyZTQxODRhOGI4NjM2Zg==
  fingerprint: !binary |-
    MTg5YjExOTJkOGIwYTM5NzExZmEzNmNlNGUyZTQxODRhOGI4NjM2Zg==
  sha1: !binary |-
    NzkyNzJjMDkzZmVlY2VmZjNhZTM4ODA5NDQxY2VlNzcwOGEwZGRkMw==
- name: tps
  version: !binary |-
    MjYyYmY2MmRmY2Q3MmJlZjBiZWY1YWI3ZDc2ZDFhNDdkNWU0MDY0Zg==
  fingerprint: !binary |-
    MjYyYmY2MmRmY2Q3MmJlZjBiZWY1YWI3ZDc2ZDFhNDdkNWU0MDY0Zg==
  sha1: !binary |-
    NWJmZWZiM2NmNjFhOGY2MzQ3Y2M2NTJlZWY2NDkwNWIzZDQzOGM4Nw==
- name: garden
  version: !binary |-
    NGQ2ZGFlMmQ5MDJmOTU2Y2Y3ODY0ZWYxOWM0ZGM0Yjc5MjZhOWM2ZA==
  fingerprint: !binary |-
    NGQ2ZGFlMmQ5MDJmOTU2Y2Y3ODY0ZWYxOWM0ZGM0Yjc5MjZhOWM2ZA==
  sha1: !binary |-
    MDFkYTcyY2EyNDgwZDVkZTI3OGJmODliNTczZDgwNjkzYWNkNzI1Nw==
- name: file_server
  version: !binary |-
    Y2E1NDc0NWU5NDJmOGU4NDM5ODQ1NjNiYWEyOWNiZTViMTNiMTFhNw==
  fingerprint: !binary |-
    Y2E1NDc0NWU5NDJmOGU4NDM5ODQ1NjNiYWEyOWNiZTViMTNiMTFhNw==
  sha1: !binary |-
    MTFiNzdiMTZiMjhkOTQxNDQ0MzM4ZjcwZWExMjRlNjIyODJiZDJmNA==
- name: nsync
  version: !binary |-
    N2FiNzNlOWVmYjJlYWUyM2JkMDNiOTBjYjNjNzg2MjgzYTFmZTQxZQ==
  fingerprint: !binary |-
    N2FiNzNlOWVmYjJlYWUyM2JkMDNiOTBjYjNjNzg2MjgzYTFmZTQxZQ==
  sha1: !binary |-
    NGY1YTI4ZjNiOWFiZWQ1NGRmODA5MTMwZmRlMzhjNTVlNWI2MTNlOQ==
- name: runtime_metrics_server
  version: !binary |-
    OThhNTAyNDUwZTczMTk1MDE4NTJiYjc2NWU0OThiZGI2NDYxNTVlNQ==
  fingerprint: !binary |-
    OThhNTAyNDUwZTczMTk1MDE4NTJiYjc2NWU0OThiZGI2NDYxNTVlNQ==
  sha1: !binary |-
    Yjk3ZjM0OTA4MWNkZjMwMjcyMThjZTJmYzRjZThlYmU1YjY2YWE3Yg==
- name: etcd_metrics_server
  version: !binary |-
    OGU4NzYzY2Y0ZDY0ZjBjYTEwM2UyOGNiOWYwMTliNGIyYzQwODFlOQ==
  fingerprint: !binary |-
    OGU4NzYzY2Y0ZDY0ZjBjYTEwM2UyOGNiOWYwMTliNGIyYzQwODFlOQ==
  sha1: !binary |-
    YjA2NGNkMmYxODhkZjZlODMyZDIzNTNmNzkwM2EwYmUwOWRhMmQwZg==
- name: auctioneer
  version: !binary |-
    N2M4MjM2MDg4ZmJhZTQzZTczNzhmMzY4MzYzN2ZlNjFiYTBiYzg1Yw==
  fingerprint: !binary |-
    N2M4MjM2MDg4ZmJhZTQzZTczNzhmMzY4MzYzN2ZlNjFiYTBiYzg1Yw==
  sha1: !binary |-
    MjNmMDhmOWIxZTcxZjU1OWRkODZlZTMxN2U2MWJiNDc1Nzg2YzkxYw==
- name: converger
  version: !binary |-
    MjUwYmQ0NTY3M2IwNzcwYzEyN2EyN2YzYmExZjFjOTg5OGVjOGM2MA==
  fingerprint: !binary |-
    MjUwYmQ0NTY3M2IwNzcwYzEyN2EyN2YzYmExZjFjOTg5OGVjOGM2MA==
  sha1: !binary |-
    ZTg3MDBlYmNjOTlhZWFmNWNjMjgwZmZkYjlkNTBlYzliNGVjZTg5ZQ==
- name: acceptance-tests
  version: !binary |-
    MTI0YjA1MDYyYmFlYWJkNGUyNzMyODZjZjE2N2Q2ZTI0NmY3MWJiNA==
  fingerprint: !binary |-
    MTI0YjA1MDYyYmFlYWJkNGUyNzMyODZjZjE2N2Q2ZTI0NmY3MWJiNA==
  sha1: !binary |-
    OTgzYjdiZTljNmEyZjBlY2IyYjNlOWFiNDBiMzQ5ZTA1YjRiNDFlNw==
- name: executor
  version: !binary |-
    MmNmNGU0NTQwNzBkNzg1Mzk1YTM4Nzg3Y2RjNWE0ZDE4ZDU3MDlmMw==
  fingerprint: !binary |-
    MmNmNGU0NTQwNzBkNzg1Mzk1YTM4Nzg3Y2RjNWE0ZDE4ZDU3MDlmMw==
  sha1: !binary |-
    ZWJkZDJkOWZlZGI3ZTlmNjc2MjFmMTZlOTY0NzY1MDViZTQ0M2E1Mw==
- name: route_emitter
  version: !binary |-
    OGI2ZjJhOTAyYjc2NmNhMzRkZDhmNDM0YjYwZTRiMTAyNGFkZGNlNA==
  fingerprint: !binary |-
    OGI2ZjJhOTAyYjc2NmNhMzRkZDhmNDM0YjYwZTRiMTAyNGFkZGNlNA==
  sha1: !binary |-
    YmM0YWRmZTA3MjQwYTA2ODU0MDMzZWRhYTEyNjc3OGZlZGE5MzM3MA==
- name: smoke-tests
  version: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  fingerprint: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  sha1: !binary |-
    YjQxNDIyZTJmN2I0NjIyMzA5NTdkOWZlZGI5MDk0MDBlNmEzOTllNg==
commit_hash: a2ee5691
uncommitted_changes: true
name: diego
version: '0.473'
